/* Chronicle dashboard: the Japanese UI strings, keyed by the exact English text (see i18n.js). */
"use strict";
window.CHRONICLE_JA = {
  // Formatting, labels
  "{n}s": "{n} 秒",
  "{d}d {h}h": "{d} 日 {h} 時間",
  "{h}h {m}m": "{h} 時間 {m} 分",
  "{m}m": "{m} 分",
  "{n}h": "{n} 時間",
  "never": "なし",
  "just now": "たった今",
  "{n} min ago": "{n} 分前",
  "{n} h ago": "{n} 時間前",
  "1 d ago": "昨日",
  "{n} d ago": "{n} 日前",
  "Fix": "修正",
  "Gotcha": "落とし穴",
  "Learning": "気づき",
  "Decision": "決定",
  "Pattern": "パターン",
  "Command": "コマンド",
  "Fact": "事実",
  "Preference": "好み",
  "Reference": "参照",
  "Todo": "TODO",
  "Fixes": "修正",
  "Gotchas": "落とし穴",
  "Learnings": "気づき",
  "Decisions": "決定",
  "Patterns": "パターン",
  "Commands": "コマンド",
  "Facts": "事実",
  "Preferences": "好み",
  "References": "参照",
  "Todos": "TODO",
  "Note": "メモ",
  "file": "ファイル",
  "concept": "概念",
  "component": "コンポーネント",
  "data": "データ",
  "domain": "ドメイン",
  "tool": "ツール",
  "library": "ライブラリ",
  "system": "システム",
  "platform": "プラットフォーム",
  "organization": "組織",
  "service": "サービス",
  "acronym": "略語",
  "person": "人物",
  "other": "その他",
  "Completed": "完了",
  "Partial": "一部完了",
  "Blocked": "行き詰まり",
  "Abandoned": "中止",
  "Exploratory": "探索",
  "Unclear": "不明",
  "queued": "待機中",
  "needs re-analysis": "再分析が必要",
  "analyzing…": "分析中…",
  "analysis failed": "分析に失敗",
  "skipped": "スキップ",
  "analyzed": "分析済み",
  "Codex Cloud task": "Codex Cloud のタスク",
  "{agent} session": "{agent} のセッション",
  "Recovered from prompt history; transcript was deleted before Chronicle": "プロンプトの履歴から復元。トランスクリプトは Chronicle の導入前に削除されていました",
  "history": "履歴",
  "Worth analyzing": "分析する価値あり",
  "Maybe": "たぶん",
  "Not worth it": "価値なし",
  "5-hour": "5 時間",
  "7-day": "7 日間",
  "spend": "利用額",
  "{limit} limit {pct}% (resets {when})": "{limit}の上限 {pct}%（{when} にリセット）",
  "as of {ago}": "取得：{ago}",
  "{limit} limit used": "{limit}の上限の使用量",
  "How far your plan limits moved while this session ran (includes anything else using the same account then)": "このセッションの実行中にプランの上限がどれだけ進んだか（同じ時間に同じアカウントを使ったものも含みます）",
  "ready now": "すぐに分析",
  "still active": "まだ作業中",
  "retry later": "後で再試行",
  "project excluded": "除外したプロジェクト",
  "too few prompts": "プロンプトが少なすぎる",
  "before install": "インストール前",
  "failed, not retried": "失敗、再試行なし",
  "Analyzed once the session has been idle for analysis.idle_minutes": "セッションが analysis.idle_minutes の間アイドルになると分析します",
  "A failed attempt is retried with a growing delay": "失敗した分析は、間隔を空けながら再試行します",
  "Turn on analysis.backfill to analyze older sessions": "古いセッションを分析するには analysis.backfill をオンにします",
  "Open the session to see the error; re-run it from its page": "セッションを開くとエラーが表示されます。そのページから再実行できます",
  "tentative": "仮",
  "seen once": "1 回のみ",
  "established": "定着",
  "canonical": "確定",
  "high confidence": "確信度：高",
  "medium confidence": "確信度：中",
  "low confidence": "確信度：低",
  // Charts, router
  "Chart": "グラフ",
  "Table": "表",
  "Daily": "日次",
  "column chart": "縦棒グラフ",
  "{n}-day average": "{n} 日平均",
  "{n}-day average {value}": "{n} 日平均 {value}",
  "activity calendar": "アクティビティカレンダー",
  "{n} day": "{n} 日",
  "{n} days": "{n} 日",
  "current streak": "現在の連続日数",
  "longest streak": "最長連続日数",
  "active days this year": "今年の稼働日数",
  "busiest day": "最も忙しかった日",
  "Mon": "月",
  "Tue": "火",
  "Wed": "水",
  "Thu": "木",
  "Fri": "金",
  "Sat": "土",
  "Sun": "日",
  "{dur} active": "稼働 {dur}",
  "No sessions": "セッションなし",
  "{n} session": "{n} セッション",
  "{n} sessions": "{n} セッション",
  "{n} prompt": "{n} プロンプト",
  "{n} prompts": "{n} プロンプト",
  "none": "なし",
  "<15m": "15 分未満",
  "15–30m": "15〜30 分",
  "30m–1h": "30 分〜1 時間",
  "1–2h": "1〜2 時間",
  "2–4h": "2〜4 時間",
  "4h+": "4 時間以上",
  "Less": "少",
  "More": "多",
  "activity by hour of week": "曜日と時間帯ごとのアクティビティ",
  "Sunday": "日曜日",
  "Monday": "月曜日",
  "Tuesday": "火曜日",
  "Wednesday": "水曜日",
  "Thursday": "木曜日",
  "Friday": "金曜日",
  "Saturday": "土曜日",
  "max": "最大",
  "Busiest hour: {when} · {n} prompts": "最も忙しい時間帯：{when} · {n} プロンプト",
  "No data": "データなし",
  "Not enough API calls to chart": "グラフにするには API 呼び出しが足りません",
  "context window per API call": "API 呼び出しごとのコンテキストウインドウ",
  "compacted": "コンパクション",
  "peak {n}": "最大 {n}",
  "{n} API calls · ticks mark prompts": "API 呼び出し {n} 回 · 目盛りはプロンプト",
  "{n} context tokens": "コンテキスト {n} トークン",
  "Call {i} · {when} · {model}": "{i} 回目の呼び出し · {when} · {model}",
  "output {out} · cache read {read} · {cost}": "出力 {out} · キャッシュ読み込み {read} · {cost}",
  "Could not load: {error}": "読み込めませんでした：{error}",
  "Not found": "見つかりません",
  "Still loading this page…": "このページを読み込んでいます…",
  "Background work: {job}": "バックグラウンドで実行中：{job}",
  // Shared widgets, Home
  "All projects": "すべてのプロジェクト",
  "Cards": "カード",
  "List": "リスト",
  "Layout": "レイアウト",
  "Nothing matches": "一致するものはありません",
  "new vs prior {n}d": "新規（前の {n} 日間比）",
  "{pct}% vs prior {n}d": "{pct}%（前の {n} 日間比）",
  "{n} a day": "1 日あたり {n}",
  "all time": "全期間",
  "the last {n} days": "直近 {n} 日間",
  "Active time: the sum of gaps under 15 minutes between events": "稼働時間：イベント間の 15 分未満の間隔の合計",
  "Active time": "稼働時間",
  "across {sessions} sessions in {projects} projects, {period}": "{period}、{projects} プロジェクトの {sessions} セッション",
  "active days": "稼働日数",
  "{a} of {b}": "{a} / {b}",
  "per active day": "稼働日あたり",
  "longest run": "最長連続",
  "Sessions": "セッション",
  "Prompts": "プロンプト",
  "Tool calls": "ツール呼び出し",
  "{n} failed · {pct}": "失敗 {n} · {pct}",
  "Lines changed": "変更行数",
  "−{n} removed": "−{n} 削除",
  "Tokens": "トークン",
  "Input + output + cache read + cache write": "入力 + 出力 + キャッシュ読み込み + キャッシュ書き込み",
  "Est. API cost": "推定 API 費用",
  "API list-price equivalent; subscriptions are billed differently. Newer GPT models are estimated at GPT-5 rates.": "API の定価換算です。サブスクリプションの請求とは異なります。新しい GPT モデルは GPT-5 の料金で見積もっています。",
  "Knowledge": "ナレッジ",
  "{n} sessions analyzed": "分析済み {n} セッション",
  "Projects": "プロジェクト",
  "most time: {name}": "最長：{name}",
  "Est. cost": "推定費用",
  "Daily {metric}": "日次の{metric}",
  "All time": "全期間",
  "Last {n} days": "直近 {n} 日間",
  "Date": "日付",
  "Outcomes": "結果",
  "from session analysis": "セッションの分析から",
  "Work types": "作業の種類",
  "Activity calendar": "アクティビティカレンダー",
  "Active time per day · click a day to see its sessions": "1 日ごとの稼働時間 · 日をクリックするとその日のセッションを表示",
  "Active": "稼働",
  "When you work": "作業する時間帯",
  "Prompts by weekday and hour, local time": "曜日と時間帯ごとのプロンプト（現地時刻）",
  "Weekday": "曜日",
  "Hour": "時",
  "by active time · sessions": "稼働時間順 · セッション数",
  "Tools": "ツール",
  "calls": "呼び出し",
  "failed": "失敗",
  "Models": "モデル",
  "est. API cost · tokens": "推定 API 費用 · トークン",
  "Agents": "エージェント",
  "Recent sessions": "最近のセッション",
  "All sessions": "すべてのセッション",
  "Latest knowledge": "最新のナレッジ",
  "Browse": "一覧へ",
  "Home": "ホーム",
  "{sessions} sessions across {projects} projects since {date}": "{date} から {projects} プロジェクトで {sessions} セッション",
  "{sessions} sessions across {projects} projects": "{projects} プロジェクトで {sessions} セッション",
  "7d": "7 日",
  "30d": "30 日",
  "90d": "90 日",
  "180d": "180 日",
  "All": "すべて",
  "All agents": "すべてのエージェント",
  "Project": "プロジェクト",
  "No sessions yet": "セッションはまだありません",
  "(untitled)": "（無題）",
  "No analyzed knowledge yet. Sessions are analyzed automatically once idle.": "分析済みのナレッジはまだありません。セッションはアイドルになると自動で分析されます。",
  "global": "グローバル",
  "Not analyzed": "未分析",
  "command": "コマンド",
  "feature": "機能",
  "bugfix": "バグ修正",
  "debugging": "デバッグ",
  "refactor": "リファクタリング",
  "research": "調査",
  "exploration": "探索",
  "ops": "運用",
  "deploy": "デプロイ",
  "config": "設定",
  "docs": "ドキュメント",
  "testing": "テスト",
  "review": "レビュー",
  "planning": "計画",
  "design": "設計",
  "learning": "学習",
  // Sessions list, export
  "Select all loaded sessions": "読み込んだセッションをすべて選択",
  "Select {name}": "{name} を選択",
  "session": "セッション",
  "Analyze {n} sessions now? Each one is a call on your {agent} login.": "{n} セッションを今すぐ分析しますか？ 1 セッションごとに、あなたの {agent} のログインで 1 回呼び出します。",
  "Starting…": "開始しています…",
  "Could not start": "開始できませんでした",
  "Analyzing {n} session; the status bar shows progress": "{n} セッションを分析しています。進み具合はステータスバーに表示されます",
  "Analyzing {n} sessions; the status bar shows progress": "{n} セッションを分析しています。進み具合はステータスバーに表示されます",
  " ({n} history-only left out: nothing to analyze)": "（履歴のみの {n} 件は対象外：分析する内容がありません）",
  "Analyze {n}": "{n} 件を分析",
  "{n} selected": "{n} 件を選択中",
  "Select all {n} matching": "一致する {n} 件をすべて選択",
  "Clear": "クリア",
  "Load more": "さらに読み込む",
  "{n} session on {date}": "{date} の {n} セッション",
  "{n} sessions on {date}": "{date} の {n} セッション",
  "No sessions match": "一致するセッションはありません",
  "Newest first": "新しい順",
  "Oldest first": "古い順",
  "Most active time": "稼働時間の長い順",
  "Most tokens": "トークンの多い順",
  "Highest est. cost": "推定費用の高い順",
  "Most tool calls": "ツール呼び出しの多い順",
  "Most prompts": "プロンプトの多い順",
  "Title A–Z": "タイトル順（A–Z）",
  "Sort sessions": "セッションの並べ替え",
  "Custom order": "カスタムの並び順",
  "Search titles, summaries and transcripts…": "タイトル、要約、トランスクリプトを検索…",
  "Started": "開始",
  "Session": "セッション",
  "Agent": "エージェント",
  "Outcome": "結果",
  "Any outcome": "すべての結果",
  "Any status": "すべての状態",
  "Analyzed": "分析済み",
  "Queued": "待機中",
  "Needs re-analysis": "再分析が必要",
  "Failed": "失敗",
  "Skipped": "スキップ",
  "Any screening": "すべての選別結果",
  "Not screened": "未選別",
  "Clear the day filter": "日付の絞り込みを解除",
  "Claude Code deleted this transcript; recovered from Codex's copy": "Claude Code がこのトランスクリプトを削除したため、Codex のコピーから復元しました",
  "recovered": "復元",
  "prompt": "プロンプト",
  "prompts": "プロンプト",
  "({n} failed)": "（失敗 {n}）",
  "Estimated API cost": "推定 API 費用",
  "Summary, knowledge and the conversation": "要約、ナレッジ、会話",
  "The full record, every event included": "すべてのイベントを含む完全な記録",
  "Original transcript": "元のトランスクリプト",
  "The agent's own file, as archived (not redacted)": "アーカイブしたままのエージェント自身のファイル（伏せ字なし）",
  "Exporting the session…": "セッションをエクスポートしています…",
  "Exporting {n} sessions as a .zip…": "{n} セッションを .zip でエクスポートしています…",
  "{n} without an original transcript are listed in its index.md.": "元のトランスクリプトがない {n} 件は index.md に一覧があります。",
  "Download as files": "ファイルとしてダウンロード",
  "Export": "エクスポート",
  "claude.ai chats share one export file; prompt-history sessions have none": "claude.ai のチャットは 1 つのエクスポートファイルを共有し、プロンプト履歴のセッションには元のファイルがありません",
  "{n} failed": "失敗 {n}",
  // Session page
  "Analyzing…": "分析中…",
  "Analysis started (via {agent}). This page refreshes when it finishes.": "分析を開始しました（{agent} を使用）。終わるとこのページが更新されます。",
  "Analysis already running": "分析はすでに実行中です",
  "Re-analyze": "再分析",
  "Analyze now": "今すぐ分析",
  "(untitled session)": "（無題のセッション）",
  "Project {name}": "プロジェクト {name}",
  "Ran in {path} there": "そのデバイスの {path} で実行",
  "on {machine}": "{machine} で実行",
  "{active} active · {wall} wall": "稼働 {active} · 経過 {wall}",
  "branch {branch}": "ブランチ {branch}",
  "The agent deleted the original; Chronicle's archive keeps it": "エージェントは元のファイルを削除しましたが、Chronicle のアーカイブに残っています",
  "original deleted · archived": "元のファイルは削除 · アーカイブ済み",
  "Claude Code deleted this transcript; Chronicle recovered it from the copy Codex Desktop imported": "Claude Code がこのトランスクリプトを削除したため、Codex Desktop が取り込んだコピーから Chronicle が復元しました",
  "recovered via Codex": "Codex から復元",
  "{n} interrupt": "中断 {n} 回",
  "{n} interrupts": "中断 {n} 回",
  "{n} subagents": "サブエージェント {n}",
  "Lines": "行数",
  "{n} file": "{n} ファイル",
  "{n} files": "{n} ファイル",
  "Peak context": "最大コンテキスト",
  "{pct}% of {size}": "{size} の {pct}%",
  "{n} compaction": "コンパクション {n} 回",
  "{n} compactions": "コンパクション {n} 回",
  "Subagents": "サブエージェント",
  "Summary": "要約",
  "analyzed {ago}": "分析：{ago}",
  "Goal": "目的",
  "Work": "作業",
  ", ": "、",
  "Mood": "雰囲気",
  "Tags": "タグ",
  "Highlights": "ハイライト",
  "Open threads": "未解決の事項",
  "Friction": "つまずき",
  ": ": "：",
  "Only prompts survive for this session (recovered from Claude Code's prompt history).": "このセッションはプロンプトしか残っていません（Claude Code のプロンプト履歴から復元）。",
  "Not analyzed yet: {reason}.": "まだ分析されていません：{reason}。",
  "Not analyzed yet ({status}: {reason}).": "まだ分析されていません（{status}：{reason}）。",
  "Not analyzed yet ({status}).": "まだ分析されていません（{status}）。",
  "Screening: ": "選別：",
  "by rule": "ルールによる",
  "First prompt": "最初のプロンプト",
  "Knowledge ({n})": "ナレッジ（{n}）",
  "Context window": "コンテキストウインドウ",
  "Tokens in context per API call (main thread)": "API 呼び出しごとのコンテキスト内のトークン（メインスレッド）",
  "Time": "時刻",
  "Model": "モデル",
  "Context": "コンテキスト",
  "Output": "出力",
  "Cost": "費用",
  "Files": "ファイル",
  "{changed} changed · {touched} touched": "変更 {changed} · 参照 {touched}",
  "File": "ファイル",
  "Reads": "読み込み",
  "Edits": "編集",
  "No files": "ファイルなし",
  "{n} tool": "{n} ツール",
  "{n} tools": "{n} ツール",
  "Pull requests": "プルリクエスト",
  "Artifacts": "成果物",
  "Workflows": "ワークフロー",
  "{n} agent": "{n} エージェント",
  "{n} agents": "{n} エージェント",
  "{n} tokens": "{n} トークン",
  "Skills": "スキル",
  "MCP servers": "MCP サーバー",
  "Slash commands": "スラッシュコマンド",
  "Analysis runs": "分析の実行",
  "Session outline": "セッションのアウトライン",
  "Files changed": "変更したファイル",
  "and {n} more": "ほか {n} 件",
  "Session view": "セッションの表示",
  "Transcript": "トランスクリプト",
  "Details": "詳細",
  "Show the prompts and files beside the transcript": "トランスクリプトの横にプロンプトとファイルを表示",
  "Outline": "アウトライン",
  "+{n} more": "+{n} 件",
  "positive": "前向き",
  "neutral": "普通",
  "frustrated": "不満",
  "mixed": "入り混じった",
  "unclear": "不明",
  "tool error": "ツールのエラー",
  "environment": "環境",
  "misunderstanding": "誤解",
  "rework": "やり直し",
  "permissions": "権限",
  "performance": "性能",
  "external": "外部要因",
  // Transcript, knowledge cards
  "Load earlier": "前を読み込む",
  "Load {n} earlier": "前の {n} 件を読み込む",
  "{a} of {b} events": "{b} 件中 {a} 件のイベント",
  "Input": "入力",
  "Error": "エラー",
  "Result": "結果",
  "(empty)": "（空）",
  "result": "結果",
  "Task prompt": "タスクのプロンプト",
  "You": "あなた",
  "queued while {agent} worked": "{agent} の作業中にキューに追加",
  "progress": "途中経過",
  "Thinking": "思考",
  "Shell": "シェル",
  "Expand tools": "ツールをすべて開く",
  "System": "システム",
  "compact": "コンパクション",
  "interrupt": "中断",
  "api error": "API エラー",
  "notice": "お知らせ",
  "notification": "通知",
  "compact summary": "コンパクションの要約",
  "meta": "メタ",
  "command output": "コマンドの出力",
  "bash output": "シェルの出力",
  "attachment": "添付",
  "Applies across projects": "プロジェクトをまたいで適用",
  "Imported from the agent's own memory notes": "エージェント自身のメモリーノートから取り込み",
  "{agent} memory": "{agent} のメモリー",
  "Show more": "さらに表示",
  "Show less": "折りたたむ",
  "Unpin": "ピン留めを外す",
  "Pin (always kept in syntheses)": "ピン留め（統合で常に残す）",
  "Pinned": "ピン留め済み",
  "Unpinned": "ピン留めを外しました",
  "Dismiss (hide and exclude from knowledge bases)": "却下（非表示にし、ナレッジベースから除外）",
  "Dismissed": "却下済み",
  "Kind": "種類",
  "From": "元",
  "Stage": "段階",
  "Confidence": "確信度",
  "Added [date]": "追加日",
  "No knowledge matches": "一致するナレッジはありません",
  // Knowledge hub and list
  "Map": "マップ",
  "Your glossary as a mindmap, by project and theme": "用語集を、プロジェクトとテーマごとのマインドマップで",
  "projects · {n} categories": "プロジェクト · {n} カテゴリ",
  "{n} themes": "{n} テーマ",
  "Drawn from the glossary once it is built": "用語集ができると描かれます",
  "All knowledge": "すべてのナレッジ",
  "Fixes, gotchas, decisions and facts from your sessions": "セッションから得た修正、落とし穴、決定、事実",
  "items · {n} from the last 7 days": "項目 · 直近 7 日間で {n} 件",
  "items": "項目",
  "Sessions are analyzed automatically once idle": "セッションはアイドルになると自動で分析されます",
  "Glossary": "用語集",
  "Every term, acronym and file name your sessions use, defined": "セッションで使われる用語、略語、ファイル名とその定義",
  "terms in {n} categories": "語 · {n} カテゴリ",
  "Built from your knowledge items": "ナレッジの項目から作られます",
  "Weekly reviews": "週次の振り返り",
  "Your week at a glance: wins, open threads, what to try next": "1 週間をひと目で：成果、未解決の事項、次に試すこと",
  "Week {n}": "第 {n} 週",
  "no reviews yet": "振り返りはまだありません",
  "Written automatically once a week's sessions are analyzed": "1 週間分のセッションが分析されると自動で書かれます",
  "Global playbook": "グローバルプレイブック",
  "Largest categories: {list}": "大きいカテゴリ：{list}",
  "{n} item": "{n} 件",
  "{n} items": "{n} 件",
  "Search knowledge…": "ナレッジを検索…",
  "All sources": "すべてのソース",
  "Extracted from sessions": "セッションから抽出",
  "Agent memory files": "エージェントのメモリーファイル",
  // Case files (事件簿): a fix, gotcha or decision that asks before it tells
  "Case files": "事件簿",
  "Fixes, gotchas and decisions told as cases: the scene, a question, then the answer": "修正・落とし穴・決定を事件として：現場、問い、そして答え",
  "Ask first": "先に問う",
  "A case you haven't answered asks its question before it shows the lesson. Your answers stay in this browser.": "まだ答えていない事件は、教訓を見せる前に問いかけます。回答はこのブラウザーにだけ残ります。",
  "No case files match. A fix, gotcha or decision gets one when its session is analyzed.": "一致する事件はありません。修正・落とし穴・決定は、そのセッションが分析されると事件簿に載ります。",
  "The scene": "現場",
  "Ruled out": "外れた手がかり",
  "{n} lead ruled out": "外れた手がかり {n} 件",
  "{n} leads ruled out": "外れた手がかり {n} 件",
  "Your call": "あなたの見立て",
  "Think of your answer first.": "まず自分の答えを考えてみてください。",
  "Show the answer": "答えを見る",
  "Skip, just show me": "スキップして答えを見る",
  "Right.": "正解。",
  "Ruled out in the session.": "セッションで外れた手がかりです。",
  "The answer:": "答え：",
  "Ask me again": "もう一度問う",
  "You skipped {n} questions in a row, so cases now open with the answer. Turn Ask first back on in All knowledge.": "{n} 問続けてスキップしたので、事件は答えから表示するようにしました。「すべてのナレッジ」の「先に問う」でいつでも戻せます。",
  // Projects, knowledge base, architecture sketch
  "Last session": "最後のセッション",
  "Knowledge base": "ナレッジベース",
  " (not on disk)": "（ディスク上にありません）",
  "updated {ago}": "更新：{ago}",
  "none yet": "まだなし",
  "No projects yet": "プロジェクトはまだありません",
  "{n} project": "{n} プロジェクト",
  "{n} projects": "{n} プロジェクト",
  "Active time per week, last 12 weeks": "週ごとの稼働時間（直近 12 週間）",
  "Week of {date}": "{date} の週",
  "not analyzed": "未分析",
  "{n} {outcome}": "{outcome} {n}",
  "{n} {agent} session": "{agent} のセッション {n} 件",
  "{n} {agent} sessions": "{agent} のセッション {n} 件",
  "not on disk": "ディスク上にありません",
  "Knowledge base updated {when}": "ナレッジベースの更新：{when}",
  "No knowledge base yet": "ナレッジベースはまだありません",
  "no KB": "KB なし",
  "Knowledge items": "ナレッジの項目",
  "Last session {ago}": "最後のセッション：{ago}",
  "12 weeks": "12 週間",
  "No playbook yet. It is built automatically once enough cross-project knowledge is analyzed, or synthesize it now.": "プレイブックはまだありません。プロジェクトをまたぐナレッジが十分に分析されると自動で作られます。今すぐ統合することもできます。",
  "No synthesized knowledge base yet. It is built automatically once a few sessions have been analyzed, or synthesize it now.": "統合されたナレッジベースはまだありません。いくつかのセッションが分析されると自動で作られます。今すぐ統合することもできます。",
  "Playbook": "プレイブック",
  "entry": "項目",
  "entries": "項目",
  "section": "セクション",
  "sections": "セクション",
  "knowledge items read": "読み込んだナレッジ",
  "projects it draws on": "元にしたプロジェクト",
  "Filter {n} entries…": "{n} 項目を絞り込み…",
  "Filter entries": "項目を絞り込み",
  "From {sources}": "出典：{sources}",
  "backed by {n} session": "{n} セッションの裏付け",
  "backed by {n} sessions": "{n} セッションの裏付け",
  "No entries match": "一致する項目はありません",
  "Read the overview": "概要を読む",
  "Read the full overview": "概要の全文を読む",
  "Code it owns": "自前のコード",
  "Way in (CLI, UI, API)": "入口（CLI、UI、API）",
  "Data it keeps": "保持するデータ",
  "External": "外部",
  "Architecture sketch: {parts} parts, {edges} connections": "構成図：要素 {parts}、つながり {edges}",
  "Click a part or a connection to see the knowledge it comes from.": "要素かつながりをクリックすると、その元になったナレッジを表示します。",
  "Connection": "つながり",
  "To": "先",
  "Based on": "根拠",
  "Download as an .excalidraw file to edit it in excalidraw.com or the Excalidraw VS Code extension": "excalidraw.com や Excalidraw の VS Code 拡張機能で編集できる .excalidraw ファイルとしてダウンロード",
  "Architecture": "アーキテクチャ",
  "Sketched from {n} knowledge item · click a part to see its sources": "{n} 件のナレッジから作図 · 要素をクリックすると出典を表示",
  "Sketched from {n} knowledge items · click a part to see its sources": "{n} 件のナレッジから作図 · 要素をクリックすると出典を表示",
  "Synthesizing…": "統合中…",
  "Synthesizing the knowledge base with {agent}…": "{agent} でナレッジベースを統合しています…",
  "Already running": "すでに実行中です",
  "Re-synthesize": "再統合",
  "Synthesize now": "今すぐ統合",
  "Cross-project learnings and your working preferences, distilled from every session": "すべてのセッションから抽出した、プロジェクトをまたぐ学びとあなたの作業の好み",
  "Most edited files": "編集の多いファイル",
  "Glossary ({n})": "用語集（{n}）",
  "open →": "開く →",
  "Sessions ({n})": "セッション（{n}）",
  // Search, glossary
  "Search all sessions": "すべてのセッションを検索",
  "Every session that mentions a word or phrase, each mention highlighted and a click away. Matches any 3+ character substring, in any language.": "語句に言及したすべてのセッションを、言及箇所をハイライトして表示します。クリックでその位置へ移動できます。言語を問わず、3 文字以上の部分文字列に一致します。",
  "subagent": "サブエージェント",
  "Loading…": "読み込み中…",
  "Showing the first {n}; open the session for the rest.": "最初の {n} 件を表示しています。残りはセッションを開いて確認してください。",
  "Show all {n} mentions": "{n} 件の言及をすべて表示",
  "{n} mention": "{n} 件の言及",
  "{n} mentions": "{n} 件の言及",
  "in summary": "要約内",
  "More sessions": "さらにセッションを表示",
  "Order sessions": "セッションの並び順",
  "Most mentions": "言及の多い順",
  "{n} knowledge item": "ナレッジ {n} 件",
  "{n} knowledge items": "ナレッジ {n} 件",
  "No sessions mention “{q}”; {n} knowledge items do": "「{q}」に言及したセッションはありません。ナレッジは {n} 件あります",
  "No sessions mention “{q}”": "「{q}」に言及したセッションはありません",
  "{agent} is rebuilding the glossary…": "{agent} が用語集を再構築しています…",
  "Rebuild this project's glossary": "このプロジェクトの用語集を再構築",
  "Rebuild glossary": "用語集を再構築",
  "Everywhere": "すべての場所",
  "not mentioned verbatim in transcripts": "トランスクリプトにはそのままの形で出てきません",
  "all mentions →": "すべての言及 →",
  "on the map →": "マップ上で見る →",
  "also {names}": "別名：{names}",
  "Term": "用語",
  "Category": "カテゴリ",
  "Definition": "定義",
  "Mentions": "言及",
  "Last seen": "最後に見た日",
  "No terms match.": "一致する用語はありません。",
  "{a} of {b} terms from your sessions. Hover underlined terms anywhere in Chronicle.": "セッションから得た {b} 語のうち {a} 語。Chronicle のどこでも、下線付きの用語にポインターを置くと定義が出ます。",
  "No glossary yet": "用語集はまだありません",
  "Search terms and definitions…": "用語と定義を検索…",
  "The glossary is built from your knowledge items. Click Rebuild glossary to create it now.": "用語集はナレッジの項目から作られます。今すぐ作るには「用語集を再構築」をクリックしてください。",
  // Map
  "Theme": "テーマ",
  "branches": "枝",
  "projects": "プロジェクト",
  "categories": "カテゴリ",
  "themes": "テーマ",
  "agents": "エージェント",
  "terms": "用語",
  "sessions": "セッション",
  "No linked sessions": "リンクされたセッションなし",
  "Not grouped yet": "未分類",
  "Your work": "あなたの作業",
  "Mindmap of glossary terms": "用語集の用語のマインドマップ",
  "click to close": "クリックで閉じる",
  "click to open": "クリックで開く",
  "{n} term": "{n} 語",
  "{n} terms": "{n} 語",
  "not mentioned verbatim": "そのままの形では言及なし",
  "Browse and filter them in the side panel": "サイドパネルで一覧・絞り込みできます",
  "{term} is hidden by the current filter": "{term} は現在の絞り込みで非表示です",
  "hidden by the current filter": "現在の絞り込みで非表示",
  "Close details": "詳細を閉じる",
  "In {path}. ": "{path} の中。",
  "mention": "言及",
  "mentions": "言及",
  "Where it is used": "使われている場所",
  "Related": "関連",
  "Learned from · {n}": "学んだ元 · {n}",
  "{n} more in Knowledge →": "ナレッジにあと {n} 件 →",
  "Mentioned most in": "最も多く言及したセッション",
  "Glossary entry": "用語集の項目",
  "All mentions": "すべての言及",
  "cross-project": "プロジェクト横断",
  "project": "プロジェクト",
  "Terms found across all your projects.": "すべてのプロジェクトで見つかった用語です。",
  "active": "稼働",
  "last session": "最後のセッション",
  "Most discussed here": "ここでよく話題になったもの",
  "Open project": "プロジェクトを開く",
  "{n} {category} terms": "{category}の用語 {n} 語",
  "Most discussed first.": "よく話題になった順です。",
  "Themes · {n}": "テーマ · {n}",
  "Most discussed": "よく話題になったもの",
  "Show as a list": "一覧で表示",
  "Terms added since this category was last grouped; they are grouped on the next run.": "このカテゴリを最後にグループ化したあとに追加された用語です。次の実行でグループ化されます。",
  "{n} terms, most discussed first.": "{n} 語、よく話題になった順です。",
  "agent": "エージェント",
  "{n} terms learned from {agent} sessions.": "{agent} のセッションから学んだ {n} 語です。",
  "about {term}": "{term} について",
  "Open session": "セッションを開く",
  "In Knowledge": "ナレッジで見る",
  "One of the sessions that mention {term} most.": "{term} に最も多く言及したセッションの 1 つです。",
  "{n} sess.": "{n} セッション",
  "Nothing matches.": "一致するものはありません。",
  "Filter {n} {what}…": "{n} 件の{what}を絞り込み…",
  "branch": "枝",
  "{n} more {what}": "ほかの{what} {n} 件",
  "Most discussed first; pick one to add it to the map.": "よく話題になった順です。選ぶとマップに追加されます。",
  "The big categories are grouped into themes: add a Theme level to see them.": "大きいカテゴリはテーマに分けてあります。見るには「テーマ」の階層を追加してください。",
  "{agent} is grouping categories into themes…": "{agent} がカテゴリをテーマに分けています…",
  "Regroup into themes": "テーマに分け直す",
  "Group into themes": "テーマに分ける",
  "{n} category has changed since grouping": "グループ化のあとに {n} カテゴリが変わりました",
  "{n} categories have changed since grouping": "グループ化のあとに {n} カテゴリが変わりました",
  "Group big categories into themes": "大きいカテゴリをテーマに分ける",
  "{agent} splits each category with 25+ terms into named themes, so no branch is a long list. One call per category ({list}).": "{agent} が 25 語以上のカテゴリを名前付きのテーマに分けるので、長い一覧になる枝はありません。カテゴリごとに 1 回呼び出します（{list}）。",
  "Your map": "あなたのマップ",
  "Views": "ビュー",
  "Shared by the most projects": "多くのプロジェクトで共通",
  "Click a node to open it; terms open into the knowledge and sessions behind them. Drag or scroll to move; pinch or ⌘-scroll to zoom.": "ノードをクリックすると開きます。用語は、その元になったナレッジとセッションに開きます。ドラッグかスクロールで移動、ピンチか ⌘＋スクロールでズームします。",
  " File names and commands are hidden.": "ファイル名とコマンドは非表示です。",
  "search": "検索",
  "“{q}”": "「{q}」",
  "Nothing on the map matches.": "マップ上に一致するものはありません。",
  "{what} match, all opened on the map and highlighted. Click one to go to it.": "{what}が一致し、すべてマップ上で開いて強調表示しています。クリックするとその位置へ移動します。",
  "{n} group": "{n} グループ",
  "{n} groups": "{n} グループ",
  "Groups": "グループ",
  "Named": "名前が一致",
  "Mentioned in the definition": "定義で言及",
  "{n} more among file names and commands. ": "ファイル名とコマンドの中にあと {n} 件あります。",
  "Show them": "表示する",
  "Search sessions": "セッションを検索",
  "Clear search": "検索をクリア",
  "Level {n}": "階層 {n}",
  "Remove": "削除",
  "Group by": "グループ化",
  "Add a level": "階層を追加",
  "+ level": "+ 階層",
  "Find terms…": "用語を探す…",
  "Find terms: every match opens on the map": "用語を探す：一致するものはすべてマップ上で開きます",
  "Dot size: sessions that mention the term": "点の大きさ：その用語に言及したセッション数",
  "Zoom out": "縮小",
  "Zoom in": "拡大",
  "Fit to screen": "画面に合わせる",
  "Collapse all": "すべて閉じる",
  "Your glossary as a mindmap: {terms} terms across {projects} projects.": "用語集のマインドマップ：{projects} プロジェクトにわたる {terms} 語。",
  "Files & commands": "ファイルとコマンド",
  "Glossary list": "用語集の一覧",
  "The map is drawn from the glossary. Build it on the Glossary page first.": "マップは用語集から描かれます。先に「用語集」ページで作成してください。",
  // Sources, MCP
  "Add": "追加",
  "Added": "追加済み",
  "Detected": "検出",
  "Not installed": "未インストール",
  "Uploading {size}B…": "{size}B をアップロード中…",
  "Import export…": "エクスポートを取り込む…",
  "An import is already running": "取り込みはすでに実行中です",
  "Importing chats…": "チャットを取り込んでいます…",
  "{n} {label}": "{label} {n}",
  "{n} issue": "問題 {n} 件",
  "{n} issues": "問題 {n} 件",
  "Connected": "接続済み",
  "Not connected": "未接続",
  "Connecting…": "接続中…",
  "syncing now": "同期中",
  "Stop recording {agent}? Recorded sessions stay in the vault.": "{agent} の記録を止めますか？ 記録済みのセッションはアーカイブに残ります。",
  "Disconnect": "切断",
  "Connect {agent}": "{agent} を接続",
  "recorded": "記録済み",
  "last {when}": "最終：{when}",
  "found on this Mac": "この Mac で検出",
  "Connect": "接続",
  "on disk": "ディスク上",
  "Claude sessions recovered": "復元した Claude のセッション",
  "Recording: {mode}": "記録：{mode}",
  "Show these chats": "これらのチャットを表示",
  "Screening is already running": "選別はすでに実行中です",
  "Screening {n} {source} chats; the status bar shows progress": "{source} のチャット {n} 件を選別しています。進み具合はステータスバーに表示されます",
  "Screen {n} chat": "{n} 件のチャットを選別",
  "Screen {n} chats": "{n} 件のチャットを選別",
  "Queue {n} chats for analysis? The background agent analyzes a few every 15 minutes, newest first, on your {agent} login.": "{n} 件のチャットを分析待ちに入れますか？ バックグラウンドのエージェントが、あなたの {agent} のログインで、15 分ごとに数件ずつ新しい順に分析します。",
  "Queued {n} chats: {per} are analyzed every 15 minutes, newest first": "{n} 件のチャットを分析待ちに入れました。15 分ごとに {per} 件ずつ、新しい順に分析します",
  "Nothing to queue": "分析待ちに入れるものはありません",
  "Queue {n} worth analyzing": "分析する価値のある {n} 件を分析待ちに入れる",
  "from a data export": "データのエクスポートから",
  "chats": "チャット",
  "worth analyzing": "分析する価値あり",
  "imported {when}": "取り込み：{when}",
  "nothing imported yet": "まだ何も取り込んでいません",
  "Imported": "取り込み済み",
  "Not imported": "未取り込み",
  "last: {file}, {new} new, {updated} updated": "前回：{file}、新規 {new}、更新 {updated}",
  "Screened:": "選別：",
  "maybe": "たぶん",
  "not worth it": "価値なし",
  "not screened": "未選別",
  "Export from {where}; the email's link downloads a .zip to import here or with {command}. Import newer exports any time: only new and changed chats are added.": "{where} からエクスポートします。届いたメールのリンクから .zip をダウンロードし、ここか {command} で取り込みます。新しいエクスポートはいつでも取り込めます。追加されるのは新しいチャットと変わったチャットだけです。",
  "Not analyzed automatically. Screening reads only each chat's opening (title, first and last prompt) to sort out the ones worth analyzing; nothing is analyzed until you queue them.": "自動では分析しません。選別は各チャットの冒頭（タイトル、最初と最後のプロンプト）だけを読み、分析する価値のあるものを選び出します。分析待ちに入れるまで何も分析しません。",
  "Sources": "ソース",
  "The coding agents Chronicle records. Connecting starts archiving and analyzing their sessions and gives the agent Chronicle's MCP tools. To give other tools the MCP server, see {link}.": "Chronicle が記録するコーディングエージェントです。接続すると、そのセッションのアーカイブと分析が始まり、エージェントが Chronicle の MCP ツールを使えるようになります。ほかのツールに MCP サーバーを使わせるには {link} を参照してください。",
  "Coding agents": "コーディングエージェント",
  "{a} of {b} connected · click a row for its checks": "{b} 件中 {a} 件を接続済み · 行をクリックするとチェック項目を表示",
  "Chat exports": "チャットのエクスポート",
  "Chats on claude.ai and chatgpt.com are not stored on your Mac, so they come in from a data export.": "claude.ai と chatgpt.com のチャットは Mac に保存されないため、データのエクスポートから取り込みます。",
  "Most clients": "ほとんどのクライアント",
  "Claude Desktop, Cursor, Windsurf, Gemini CLI, Cline, Zed and most others: add to the client's MCP config (an mcpServers object).": "Claude Desktop、Cursor、Windsurf、Gemini CLI、Cline、Zed など、ほとんどのクライアント：クライアントの MCP 設定（mcpServers オブジェクト）に追加します。",
  "VS Code (Copilot Chat): the user mcp.json (⌘⇧P › MCP: Open User Configuration) or .vscode/mcp.json in a workspace.": "VS Code（Copilot Chat）：ユーザーの mcp.json（⌘⇧P › MCP: Open User Configuration）か、ワークスペースの .vscode/mcp.json に追加します。",
  "OpenAI Codex: ~/.codex/config.toml.": "OpenAI Codex：~/.codex/config.toml に追加します。",
  "Claude Code: run this in a terminal (user scope: every project).": "Claude Code：ターミナルで実行します（ユーザースコープ：すべてのプロジェクト）。",
  "Have we solved this before? The build fails with …": "前にもこれを解決した？ ビルドが … で失敗する",
  "How is this project deployed?": "このプロジェクトはどうやってデプロイしている？",
  "What did I decide about … last month, and why?": "先月 … について何を、なぜ決めた？",
  "What does the term … mean here?": "ここで「…」という用語はどういう意味？",
  "Summarize what I worked on this week.": "今週の作業を要約して。",
  "Copied": "コピーしました",
  "Not added": "未追加",
  "Fix in Sources": "ソースで修正",
  "Copy": "コピー",
  "Chronicle's MCP server lets an agent search your past sessions, knowledge and glossary while it works. It runs on your Mac, only reads, and needs no network.": "Chronicle の MCP サーバーを使うと、エージェントが作業中に過去のセッション、ナレッジ、用語集を検索できます。Mac 上で動き、読み取りだけを行い、ネットワークは使いません。",
  "Connecting an agent in {link} also gives it the MCP server.": "{link}でエージェントを接続すると、MCP サーバーも使えるようになります。",
  "Other MCP clients": "ほかの MCP クライアント",
  "Not recorded: they only get the MCP server. Add writes Chronicle into the client's own config (backed up first); restart the client to load it.": "記録はしません。MCP サーバーだけを使えます。「追加」でクライアント自身の設定に Chronicle を書き込みます（事前にバックアップします）。読み込むにはクライアントを再起動してください。",
  "Add it to any other client": "ほかのクライアントに追加",
  "Chronicle speaks MCP over stdio: the client starts {command} and talks to it. No port, token or environment variable is needed.": "Chronicle は stdio で MCP を話します。クライアントが {command} を起動してやり取りします。ポート、トークン、環境変数は必要ありません。",
  "all read-only": "すべて読み取り専用",
  "Try asking": "聞いてみる",
  "Answers join the client's conversation, so they reach that client's model; secrets are redacted as in analysis digests. Give the server only to clients whose model provider you trust with your sessions.": "回答はクライアントの会話に加わるため、そのクライアントのモデルに届きます。機密情報は分析のダイジェストと同じように伏せ字にします。このサーバーは、セッションを任せられるモデル提供元のクライアントにだけ使わせてください。",
  // Weekly reviews, Status
  "W{n}": "第 {n} 週",
  "same as the week before": "前の週と同じ",
  "{pct}% vs the week before": "{pct}%（前の週比）",
  "Week {period}": "{period} の週",
  "Lines added": "追加行数",
  "API list-price equivalent; subscriptions are billed differently": "API の定価換算です。サブスクリプションの請求とは異なります",
  "Day by day": "日ごと",
  "active time": "稼働時間",
  "Where the time went": "時間の使い道",
  "active time · sessions": "稼働時間 · セッション数",
  "How it went": "結果",
  "session outcomes": "セッションの結果",
  "Knowledge captured": "得られたナレッジ",
  "Shipped": "出荷したもの",
  "Learned": "学んだこと",
  "Still open": "未解決の事項",
  "Slowed you down": "足を引っ張ったもの",
  "Try next": "次に試すこと",
  "Overturned": "覆された項目",
  "Read the full write-up": "全文を読む",
  "Themes": "テーマ",
  "{agent} is writing the review…": "{agent} が振り返りを書いています…",
  "Week": "週",
  "Review of {week} will be written on the next background run": "{week} の振り返りは、次のバックグラウンドの実行で書かれます",
  "A new review is written automatically each week once its sessions are analyzed": "その週のセッションが分析されると、毎週新しい振り返りが自動で書かれます",
  "Written automatically once a week's sessions are analyzed ({week}: {note})": "1 週間分のセッションが分析されると自動で書かれます（{week}：{note}）",
  "Rewrite {week}": "{week}を書き直す",
  "Write {week}": "{week}を書く",
  "This week so far": "今週のここまで",
  "No reviews yet. One is written automatically once a week's sessions are analyzed, or write one now.": "振り返りはまだありません。1 週間分のセッションが分析されると自動で書かれます。今すぐ書くこともできます。",
  "Updates": "アップデート",
  "Chronicle {version} is available": "Chronicle {version} が利用できます",
  "What's new": "新機能",
  "Checking pypi.org for the latest version…": "pypi.org で最新のバージョンを確認しています…",
  "Not checked yet. Checking asks pypi.org for the latest version.": "まだ確認していません。確認すると pypi.org に最新のバージョンを問い合わせます。",
  "You're on the latest version (checked {ago})": "最新のバージョンです（確認：{ago}）",
  "Checking…": "確認中…",
  "Check for updates": "アップデートを確認",
  "Reinstall from checkout": "チェックアウトから再インストール",
  "Reinstall": "再インストール",
  "Update to {version}": "{version} にアップデート",
  "Updating…": "アップデート中…",
  "An update is already running": "アップデートはすでに実行中です",
  "Updating Chronicle; the dashboard restarts when it is done": "Chronicle をアップデートしています。終わるとダッシュボードが再起動します",
  "Restarting Chronicle": "Chronicle を再起動しています",
  "Restarting Chronicle…": "Chronicle を再起動しています…",
  "The update is installed. This page reloads by itself when the dashboard is back.": "アップデートをインストールしました。ダッシュボードが戻るとこのページは自動で再読み込みされます。",
  "The dashboard is taking longer than usual to come back.": "ダッシュボードの再起動にいつもより時間がかかっています。",
  "Reload": "再読み込み",
  "Updating Chronicle…": "Chronicle をアップデートしています…",
  "Check for updates daily": "毎日アップデートを確認",
  "Notify me about new versions": "新しいバージョンを通知",
  "Download {version}": "{version} をダウンロード",
  "installed {ago}": "インストール：{ago}",
  "Asks pypi.org for the latest version number once a day while Chronicle is open. Sends nothing about you.": "Chronicle を開いている間、1 日 1 回 pypi.org に最新のバージョン番号を問い合わせます。あなたについての情報は何も送りません。",
  "A desktop notification when a new version is out, even with the dashboard closed: the background sync asks pypi.org once a day. Sends nothing about you.": "新しいバージョンが出るとデスクトップに通知します。ダッシュボードを閉じていても、バックグラウンドの同期が 1 日 1 回 pypi.org に問い合わせます。あなたについての情報は何も送りません。",
  "Runs {command}, then restarts the dashboard.": "{command} を実行し、ダッシュボードを再起動します。",
  "Runs {command}. Quit and reopen Chronicle afterwards.": "{command} を実行します。終わったら Chronicle を終了して開き直してください。",
  "Your checkout is at {latest}; this install is {current}": "チェックアウトは {latest}、このインストールは {current} です",
  "Your checkout has {n} new commit since this install": "このインストールのあと、チェックアウトに新しいコミットが {n} 件あります",
  "Your checkout has {n} new commits since this install": "このインストールのあと、チェックアウトに新しいコミットが {n} 件あります",
  "Your checkout's files have changed since this install": "このインストールのあと、チェックアウトのファイルが変わりました",
  "Commits": "コミット",
  "Show {n} more": "ほか {n} 件を表示",
  "{n} changed file": "変更したファイル {n} 件",
  "{n} changed files": "変更したファイル {n} 件",
  " (not committed yet)": "（未コミット）",
  "Sessions are now analyzed with {agent}.": "これからセッションは {agent} で分析されます。",
  "Analyzed by": "分析に使うエージェント",
  "{agent} is not installed": "{agent} はインストールされていません",
  "Analyzed by {agent} through your own login; only a redacted digest of each session is sent.": "あなた自身のログインを通じて {agent} で分析します。送るのは各セッションの伏せ字済みのダイジェストだけです。",
  "{agent} was not found: sessions wait in the queue until it is installed and signed in.": "{agent} が見つかりません。インストールしてサインインするまで、セッションはキューで待機します。",
  "Could not change the knowledge language": "ナレッジの言語を変更できませんでした",
  "Knowledge is now written in {language}.": "これからナレッジは{language}で書かれます。",
  "Knowledge language": "ナレッジの言語",
  "Language of summaries, knowledge, reviews and the lines proposed for CLAUDE.md and AGENTS.md. Applies to sessions analyzed from now on.": "要約、ナレッジ、振り返り、CLAUDE.md と AGENTS.md に提案する行の言語です。これから分析するセッションに適用されます。",
  "Status": "ステータス",
  "last sync {ago}": "最後の同期：{ago}",
  "Recording": "記録",
  "SessionEnd hook": "SessionEnd フック",
  "archives + ingests each session as it ends": "各セッションの終了時にアーカイブして取り込み",
  "Background agent": "バックグラウンドのエージェント",
  "runs every 15 min · {n} runs · last exit {code}": "15 分ごとに実行 · 実行 {n} 回 · 最後の終了コード {code}",
  "not loaded": "読み込まれていません",
  "MCP server registered": "MCP サーバーを登録済み",
  "Claude Code can search this vault": "Claude Code がこのアーカイブを検索できます",
  "SessionStart knowledge injection": "SessionStart でのナレッジの注入",
  "optional: {command}": "任意：{command}",
  "Status-line usage collector": "ステータスラインの使用量の収集",
  "no plan limits seen yet (Pro and Max plans only)": "プランの上限はまだ記録されていません（Pro と Max プランのみ）",
  "Storage": "保存場所",
  " raw transcripts (kept forever, gzip)": " 元のトランスクリプト（無期限に保存、gzip）",
  " Markdown vault": " Markdown の保管庫",
  "Database {size}B": "データベース {size}B",
  "Analysis": "分析",
  "Model {model} · auto {auto} · backfill {backfill} · {n} per run": "モデル {model} · 自動 {auto} · backfill {backfill} · 1 回 {n} 件",
  "on": "オン",
  "off": "オフ",
  "Waiting because: ": "待機の理由：",
  "Paused until {when} (usage limit)": "{when} まで一時停止中（使用量の上限）",
  "Recent failures": "最近の失敗",
  // Devices, suggestion helpers
  "Records and analyzes its own sessions.": "自分のセッションを記録して分析します。",
  "The hub: records and analyzes its own sessions and the ones your other computers send it.": "ハブ：自分のセッションと、ほかのコンピューターから送られたセッションを記録して分析します。",
  "This computer": "このコンピューター",
  "Last sent {ago}: {summary}": "最後の送信（{ago}）：{summary}",
  "Open the hub's dashboard": "ハブのダッシュボードを開く",
  "On your phone": "スマートフォンで",
  "This dashboard is on your tailnet at {url}. Open it on your phone with the Tailscale app on, then add it to the Home Screen (iPhone: Share › Add to Home Screen) to open it like an app.": "このダッシュボードは tailnet の {url} にあります。Tailscale アプリをオンにしたスマートフォンで開き、ホーム画面に追加すると（iPhone：共有 › ホーム画面に追加）アプリのように開けます。",
  "Only {users} can open it. Nothing is reachable from the internet.": "開けるのは {users} だけです。インターネットからはアクセスできません。",
  "Anyone in your tailnet can open it. Nothing is reachable from the internet.": "tailnet の誰でも開けます。インターネットからはアクセスできません。",
  "{command} takes it off the tailnet.": "{command} で tailnet から外せます。",
  "Open this dashboard on your phone through Tailscale, a private network between your own devices: nothing is opened to the internet, and only your Tailscale login gets in. Install Tailscale on this computer and your phone, sign both in to the same account, then run here:": "自分のデバイス同士をつなぐプライベートネットワーク Tailscale を通じて、スマートフォンでこのダッシュボードを開けます。インターネットには何も公開されず、入れるのはあなたの Tailscale のログインだけです。このコンピューターとスマートフォンに Tailscale をインストールし、両方で同じアカウントにサインインしてから、ここで次を実行します：",
  "Computer": "コンピューター",
  "Latest session": "最新のセッション",
  "Last sent": "最後の送信",
  " (this one)": "（このコンピューター）",
  "nothing yet": "まだなし",
  "Computers": "コンピューター",
  "{n} sending here": "{n} 台が送信中",
  "To add a computer, run {command} here: it prints the command to run on the other one. Sessions from each computer are matched to the same projects here by their git remote.": "コンピューターを追加するには、ここで {command} を実行します。もう一方で実行するコマンドが表示されます。各コンピューターのセッションは、git のリモートをもとに、ここで同じプロジェクトにまとめられます。",
  "Folders mapped ([hub] path_map)": "対応付けたフォルダー（[hub] path_map）",
  "Keep the sessions of your other computers here too. This computer becomes the hub, the only one that records and analyzes (so each session is analyzed once); the others send it their Claude Code and Codex sessions over your tailnet. Run here:": "ほかのコンピューターのセッションもここにまとめられます。このコンピューターがハブになり、記録と分析はここだけで行います（各セッションの分析は 1 回だけです）。ほかのコンピューターは、Claude Code と Codex のセッションを tailnet 経由でここに送ります。ここで次を実行します：",
  "It prints a {command} command to run on each other computer.": "ほかの各コンピューターで実行する {command} コマンドが表示されます。",
  "Devices": "デバイス",
  "One Chronicle for your computers and your phone.": "コンピューターとスマートフォンで、1 つの Chronicle を。",
  "Instruction": "指示",
  "Config change": "設定の変更",
  "Setup step": "セットアップ手順",
  "To review": "確認待ち",
  "Applied": "適用済み",
  "Done": "完了",
  "Stale": "古くなった",
  "Tool use": "ツールの使い方",
  "MCP setup": "MCP の設定",
  "Environment": "環境",
  "Agent behaviour": "エージェントの振る舞い",
  "Permissions": "権限",
  "Noise": "ノイズ",
  "Other": "その他",
  "your shell (you run it)": "あなたのシェル（あなたが実行）",
  "Setup steps": "セットアップ手順",
  "Chronicle shows the command; you run it and mark it done": "Chronicle はコマンドを表示するだけです。あなたが実行し、完了にします",
  "Claude Code's MCP servers": "Claude Code の MCP サーバー",
  "Codex and other agents that read AGENTS.md": "Codex など、AGENTS.md を読むエージェント",
  "Read by every {reader} session": "{reader} のすべてのセッションが読みます",
  "read by {reader} in this project": "このプロジェクトで {reader} が読みます",
  "seen in {n} session since applied": "適用後に {n} セッションで発生",
  "seen in {n} sessions since applied": "適用後に {n} セッションで発生",
  "not seen since applied": "適用後は発生なし",
  "Anyone can read this repository, so anyone can read this line": "このリポジトリは誰でも読めるため、この行も誰でも読めます",
  "Public repository": "公開リポジトリ",
  "Looks sensitive: {items}": "機密情報の可能性：{items}",
  "git does not track this file, so the line stays on this computer": "このファイルは git で管理されていないため、この行はこのコンピューターにだけ残ります",
  "File not tracked by git": "git で管理されていないファイル",
  "Already covered in this file": "このファイルですでに扱っています",
  "No change: the file already says this.": "変更なし：ファイルにすでに書かれています。",
  "Changes to the file": "ファイルへの変更",
  "Suggestions, {n} new": "提案（新着 {n} 件）",
  "Suggestions": "提案",
  // Suggestion cards
  "Not applied: {error}": "適用できませんでした：{error}",
  "unknown error": "不明なエラー",
  "Added to {path} (the previous file is backed up)": "{path} に追加しました（元のファイルはバックアップ済みです）",
  "Could not undo: {error}": "元に戻せませんでした：{error}",
  "Taken back out of {path}": "{path} から取り除きました",
  "Back in the queue": "確認待ちに戻しました",
  "Could not dismiss: {error}": "却下できませんでした：{error}",
  "Could not mark it done": "完了にできませんでした",
  "Line to add: {title}": "追加する行：{title}",
  "could not check the text": "文言を確認できませんでした",
  "Your text looks sensitive: read the warning, then Apply again to write it": "文言に機密情報が含まれている可能性があります。警告を読んでから、もう一度「適用」を押すと書き込みます",
  "Reset to the proposed text": "提案された文言に戻す",
  "Apply": "適用",
  "Restore": "復元",
  "Undo": "元に戻す",
  "Dismiss": "却下",
  "Mark done": "完了にする",
  "Preview": "プレビュー",
  "Could not preview": "プレビューできませんでした",
  "Hide preview": "プレビューを隠す",
  "Marked done {ago}": "完了：{ago}",
  "Applied {ago}": "適用：{ago}",
  "Undoing…": "元に戻しています…",
  "Dismissed: {reason}": "却下済み：{reason}",
  "Restoring…": "復元しています…",
  "Saving…": "保存しています…",
  "Dismissing…": "却下しています…",
  "Applying…": "適用しています…",
  "Put it in your user-level file instead, which every project reads": "代わりに、すべてのプロジェクトが読むユーザーレベルのファイルに入れます",
  "Put it in the file of each project it came from instead (up to 5)": "代わりに、元になった各プロジェクトのファイルに入れます（最大 5 つ）",
  "Moving…": "移しています…",
  "Could not move it: {error}": "移せませんでした：{error}",
  "Moved to {targets}": "{targets} に移しました",
  "Moved, but it was dismissed or applied there before": "移しましたが、移した先ではすでに却下または適用されていました",
  "Move to every project": "すべてのプロジェクトに移す",
  "Move to {name} only": "{name} だけに移す",
  "Move to its projects": "元のプロジェクトに移す",
  "from knowledge": "ナレッジから",
  "from what goes wrong": "「うまくいかないこと」から",
  "The cause has not been seen lately": "この原因は最近起きていません",
  "not seen lately": "最近は発生なし",
  "Applied to {path}": "{path} に適用しました",
  "Marked done": "完了にしました",
  "Copy command": "コマンドをコピー",
  "Read the warnings and the change first": "先に警告と変更内容を確認してください",
  "Review": "確認する",
  "Approve": "承認",
  "Approving…": "承認しています…",
  "{n} to review · nothing is written until you approve": "確認待ち {n} 件 · 承認するまで何も書き込みません",
  "All suggestions": "すべての提案",
  // Suggestions page, What goes wrong, Appearance
  "Where": "場所",
  "User level (every project)": "ユーザーレベル（すべてのプロジェクト）",
  "Look at the latest sessions and knowledge for new suggestions": "最新のセッションとナレッジから新しい提案を探します",
  "Could not check: {error}": "確認できませんでした：{error}",
  "{new} new, {updated} updated, {stale} no longer happening": "新規 {new}、更新 {updated}、起きなくなったもの {stale}",
  "Check again": "もう一度確認",
  "{n} suggestion": "提案 {n} 件",
  "{n} suggestions": "提案 {n} 件",
  "Nothing to suggest yet. After a sync, Chronicle proposes a fix once a failure keeps coming back, or once knowledge is confirmed often enough to belong in an instruction file.": "提案はまだありません。同期のあと、失敗が繰り返し起きたとき、またはナレッジが指示ファイルに入れるべきほど十分に裏付けられたときに、Chronicle が修正を提案します。",
  "Nothing {status} here.": "ここには「{status}」の提案はありません。",
  "Nothing {status}.": "「{status}」の提案はありません。",
  "Show everything": "すべて表示",
  "Fixes for what keeps going wrong, and knowledge worth telling your agents. Nothing is written until you apply it; the file is backed up first.": "繰り返しうまくいかないことへの修正と、エージェントに伝える価値のあるナレッジです。適用するまで何も書き込まず、書き込む前にファイルをバックアップします。",
  "What goes wrong": "うまくいかないこと",
  "Only the fixes for “{cause}”. ": "「{cause}」の修正だけを表示しています。",
  "Show all": "すべて表示",
  "of sessions in those projects": "それらのプロジェクトのセッションに占める割合",
  "occurrences": "発生回数",
  "retried the same way": "同じ方法で再試行",
  "first seen": "最初に見た日",
  "Examples": "例",
  "Cause": "原因",
  "Last 12 weeks": "直近 12 週間",
  "Expected failures need no fix": "想定内の失敗に修正は不要です",
  "{n} to review": "確認待ち {n} 件",
  "applied": "適用済み",
  "Recurring, but there is no known fix to propose": "繰り返し起きていますが、提案できる既知の修正がありません",
  "Not frequent enough to propose a fix": "修正を提案するほど頻繁ではありません",
  "still happening": "まだ起きている",
  "expected": "想定内",
  "quiet lately": "最近は起きていない",
  "Sessions per week: {list}": "週ごとのセッション数：{list}",
  "No recurring causes in this period": "この期間に繰り返し起きた原因はありません",
  "Tools that fail most": "失敗の多いツール",
  "failed calls, duplicates counted once": "失敗した呼び出し（重複は 1 回と数える）",
  "Tool": "ツール",
  "Calls": "呼び出し",
  "Rate": "割合",
  "No failed tool calls": "失敗したツール呼び出しはありません",
  "Show": "表示",
  "Hide": "隠す",
  "expected failures, left out above": "想定内の失敗（上の一覧には含めません）",
  "{n} failures in {sessions} sessions were expected: tests failing inside a dev loop, read-only command chains that ended non-zero, provider outages and tool calls you turned down.": "{sessions} セッションの {n} 件の失敗は想定内でした：開発ループの中で失敗するテスト、0 以外で終わった読み取り専用のコマンドの連鎖、提供元の障害、あなたが断ったツール呼び出しです。",
  "No expected failures in this period.": "この期間に想定内の失敗はありません。",
  "Recurring failure causes across your sessions, noise kept apart. {n} still happening; fixes wait in {link}.": "セッションで繰り返し起きる失敗の原因です（ノイズは分けてあります）。まだ起きているものは {n} 件で、修正は{link}にあります。",
  "Recurring failure causes across your sessions, noise kept apart. Fixes wait in {link}.": "セッションで繰り返し起きる失敗の原因です（ノイズは分けてあります）。修正は{link}にあります。",
  "Causes": "原因",
  "click a row for examples and fixes": "行をクリックすると例と修正を表示",
  "Appearance": "外観",
  "Saved in this browser (and in the app window).": "このブラウザー（とアプリのウインドウ）に保存されます。",
  "System follows your Mac's light or dark setting.": "「システム」は Mac のライト／ダークの設定に従います。",
  "Light": "ライト",
  "Dark": "ダーク",
  "Language": "言語",
  "System follows your browser's language. The page reloads to switch.": "「システム」はブラウザーの言語設定に従います。切り替えるとページを再読み込みします。",
  "Sidebar": "サイドバー",
  "The button at the top left, or ⌘B, shows or hides it. While it's hidden, pointing at the rail brings it out until the pointer moves away.": "左上のボタンか ⌘B で表示／非表示を切り替えます。非表示の間は、レールにポインタを合わせると一時的に表示され、離すと隠れます。",
  "Toggle sidebar": "サイドバーの表示を切り替え",
  "Settings": "設定",
  // Shell: crumbs, rail, sidebar, palette, status bar
  "Search": "検索",
  "Today": "今日",
  "Yesterday": "昨日",
  "Previous 7 days": "過去 7 日間",
  "Previous 30 days": "過去 30 日間",
  "Filter sessions": "セッションを絞り込み",
  "Overview": "概要",
  "Kinds": "種類",
  "Explore": "探す",
  "Most recent first": "新しい順",
  "No projects match": "一致するプロジェクトはありません",
  "Filter projects": "プロジェクトを絞り込み",
  "Understand": "理解する",
  "{section} navigation": "{section}のナビゲーション",
  "Go to": "移動",
  "uses the analysis model": "分析モデルを使います",
  "fixes to approve": "承認待ちの修正",
  "recurring failures": "繰り返し起きる失敗",
  "connect other agents": "ほかのエージェントを接続",
  "phone, other computers": "スマートフォン、ほかのコンピューター",
  "Sync now": "今すぐ同期",
  "Switch to light theme": "ライトテーマに切り替え",
  "Switch to dark theme": "ダークテーマに切り替え",
  "Group glossary themes": "用語集をテーマに分ける",
  "{agent} is grouping the glossary into themes…": "{agent} が用語集をテーマに分けています…",
  "Rebuild the glossary": "用語集を再構築",
  "Search all sessions for “{q}”": "すべてのセッションで「{q}」を検索",
  "Search sessions, knowledge, terms and commands": "セッション、ナレッジ、用語、コマンドを検索",
  "Search or run a command": "検索またはコマンドを実行",
  "Search or jump to": "検索または移動",
  "move": "移動",
  "open": "開く",
  "open this": "これを開く",
  "Analysis paused until {time}": "{time} まで分析を一時停止中",
  "Up to date": "最新の状態",
  "{n} session queued for analysis": "分析待ち {n} セッション",
  "{n} sessions queued for analysis": "分析待ち {n} セッション",
  "Sends its sessions to {host}": "セッションを {host} に送信",
  "Synced {ago}": "同期：{ago}",
  "Not synced yet": "まだ同期していません",
  "Done: {result}": "完了：{result}",
  "Failed: {result}": "失敗：{result}",
  "Sync": "同期",
  "Importing chats": "チャットの取り込み",
  "Screening imported chats": "取り込んだチャットの選別",
  "Updating Chronicle": "Chronicle のアップデート",
  "Grouping glossary themes": "用語集のテーマ分け",
  "Analyzing selected sessions": "選択したセッションの分析",
  "Analyzing session {id}": "セッション {id} の分析",
  "Glossary: {name}": "用語集：{name}",
  "Weekly review": "週次の振り返り",
  "Knowledge base: {name}": "ナレッジベース：{name}",
  "{m}m {s}s": "{m} 分 {s} 秒",
  "starting…": "開始中…",
  "{time} so far": "経過 {time}",
  "about {time} left": "残り約 {time}",
  "done": "完了",
  "Analysis paused until {time} ({agent} usage limit or sign-in); it resumes by itself.": "{time} まで分析を一時停止しています（{agent} の使用量の上限またはサインイン）。自動で再開します。",
  "Nothing waiting for analysis.": "分析待ちはありません。",
  "{n} session waiting for analysis": "分析待ち {n} セッション",
  "{n} sessions waiting for analysis": "分析待ち {n} セッション",
  ", but {reason}.": "。ただし、{reason}。",
  "; the background agent analyzes up to {n} every 15 minutes.": "。バックグラウンドのエージェントが 15 分ごとに最大 {n} 件を分析します。",
  "{n} held until a setting changes (see Status).": "設定が変わるまで {n} 件を保留しています（「ステータス」を参照）。",
  "Activity": "アクティビティ",
  "Close": "閉じる",
  "Nothing running right now.": "いま実行中の処理はありません。",
  "Recent": "最近",
  "Update available": "アップデートがあります",
  "Open Status to update Chronicle": "「ステータス」を開いて Chronicle をアップデート",
  "Chronicle updated to {version}": "Chronicle を {version} にアップデートしました",
  "Chronicle updated": "Chronicle をアップデートしました",
  "Your checkout has new changes": "チェックアウトに新しい変更があります",
  "Reinstall to run them in the dashboard.": "ダッシュボードで使うには再インストールしてください。",
  "You're on {version}. Update from Settings › Status.": "現在は {version} です。「設定 › ステータス」からアップデートできます。",
  "View update": "アップデートを見る",
  "Later": "後で",
  "Dismiss [notification]": "閉じる",
  "Syncing transcripts and processing the queue…": "トランスクリプトを同期し、キューを処理しています…",
  "A sync is already running": "同期はすでに実行中です",
  "Chronicle home": "Chronicle のホーム",
  "Sections": "セクション",
  "Toggle sidebar (⌘B)": "サイドバーの表示を切り替え（⌘B）",
  "Back": "戻る",
  "Forward": "進む",
  "Search or jump to (⌘K)": "検索または移動（⌘K）",
  "Search or jump to…": "検索または移動…",
  "Sync transcripts and process the analysis queue": "トランスクリプトを同期し、分析のキューを処理します",
  "Toggle theme": "テーマを切り替え",
  "Background work: click for progress": "バックグラウンドの処理：クリックで進み具合を表示",
  // Artifacts: what sessions made
  "Documents": "ドキュメント",
  "document": "ドキュメント",
  "Pages": "ページ",
  "page": "ページ",
  "Diagrams": "図",
  "diagram": "図",
  "Decks": "スライド",
  "deck": "スライド",
  "Sheets": "スプレッドシート",
  "sheet": "スプレッドシート",
  "Images": "画像",
  "image": "画像",
  "Image": "画像",
  "Published": "公開リンク",
  "published link": "公開リンク",
  "pull request": "プルリクエスト",
  "commit": "コミット",
  "The file is on disk as the agent wrote it": "エージェントが書いたときのままディスク上にあります",
  "changed since": "その後に変更",
  "The file is on disk, but changed after the agent wrote it": "ディスク上にありますが、エージェントが書いたあとに変更されています",
  "gone": "なし",
  "The file is no longer on disk; the session's transcript still holds what was written": "ディスク上にはもうありません。書いた内容はセッションのトランスクリプトに残っています",
  "in the chat": "チャット内",
  "Made in a claude.ai chat; it lives there, not on this machine": "claude.ai のチャットで作ったもので、このコンピューターではなくそちらにあります",
  "another machine": "別のコンピューター",
  "Made on another of your machines": "あなたの別のコンピューターで作ったものです",
  "Gone from disk: open it as the agent wrote it": "ディスクからなくなっています：エージェントが書いたときの内容で開きます",
  "Open the file in a new tab": "新しいタブでファイルを開く",
  "It lives in this claude.ai chat: open it there": "この claude.ai のチャットにあります：そちらで開きます",
  "Open where the session made it": "セッションで作った位置を開く",
  "Open": "開く",
  "It lives in this claude.ai chat: open it there to download it": "この claude.ai のチャットにあります：そちらで開いてダウンロードできます",
  "{n} version": "{n} 版",
  "{n} versions": "{n} 版",
  "View": "表示",
  "View {title}": "{title} を表示",
  "The session that made it": "これを作ったセッション",
  "Open on this Mac": "この Mac で開く",
  "Open on this computer": "このコンピューターで開く",
  "In the app that opens this kind of file": "この種類のファイルを開くアプリで",
  "Show in Finder": "Finder で表示",
  "Show in its folder": "フォルダーで表示",
  "Copy the path": "パスをコピー",
  "More for {title}": "{title} のその他の操作",
  "Shown in Finder": "Finder で表示しました",
  "Opened its folder": "フォルダーを開きました",
  "Open the claude.ai chat it lives in": "これがある claude.ai のチャットを開く",
  "In claude.ai ↗": "claude.ai で開く ↗",
  "No longer on disk": "ディスク上にありません",
  "Made in: {title}": "作成元：{title}",
  "Open original": "元のファイルを開く",
  "Path copied": "パスをコピーしました",
  "Search titles, paths and links…": "タイトル、パス、リンクを検索…",
  "Search artifacts": "成果物を検索",
  "Hide files that are gone": "なくなったファイルを隠す",
  "{n} shown": "{n} 件を表示",
  "Nothing matches these filters.": "この条件に合うものはありません。",
  "No artifacts yet. They are recorded as sessions sync: files an agent creates, pages it publishes, PRs it opens and commits it makes.": "まだ成果物はありません。セッションの同期とともに記録されます：エージェントが作ったファイル、公開したページ、作った PR、コミット。",
  "What your agents made, each linked to the session that made it, and whether it is still where they left it": "エージェントが作ったもの。それぞれ作ったセッションにリンクし、今もそこにあるかを示します",
  "Everything": "すべて",
  "All →": "すべて →",
  "{n} made in this session": "このセッションで作ったもの {n} 件",
  "Made": "作ったもの",
  "what your agents made": "エージェントが作ったもの",
  "{repo} goes to {project} instead: the hub knows its git remote": "{repo} は {project} に入ります（ハブがその git リモートを知っているため）",
  "Folders added on other computers": "ほかのコンピューターで追加したフォルダー",
  "Sessions in these folders go to the project shown, unless a repository inside has a git remote this hub knows.": "これらのフォルダーのセッションは、表示のプロジェクトに入ります。ただし、中のリポジトリの git リモートをこのハブが知っている場合は、そのリモートに従います。",
  "Analyzes its own sessions and sends only summaries and project lessons": "自分でセッションを分析し、要約とプロジェクトのナレッジだけを送ります",
  " · knowledge only": " · ナレッジのみ",
  // Devices › what this computer sends, team store
  "Send this computer's transcripts to the hub? The hub then records and analyzes them, and this computer stops analyzing its own sessions.": "このコンピューターのトランスクリプトをハブに送りますか？ ハブがそれを記録・分析し、このコンピューターは自分のセッションを分析しなくなります。",
  "This computer now shares only summaries and project lessons.": "このコンピューターは要約とプロジェクトのナレッジだけを共有します。",
  "This computer now sends its transcripts to the hub.": "このコンピューターはトランスクリプトをハブに送ります。",
  "Sending to the hub…": "ハブに送信中…",
  "Already sending": "すでに送信中です",
  "Send now": "今すぐ送る",
  "Summaries and lessons": "要約とナレッジ",
  "Transcripts": "トランスクリプト",
  "Change this on the computer itself, not from another device.": "この設定は、ほかのデバイスからではなく、このコンピューター自身で変更してください。",
  "Checking the team store…": "チームストアを確認中…",
  "Off: what computers share is kept in this hub's own database only.": "オフ：各コンピューターが共有したものは、このハブ自身のデータベースにだけ残ります。",
  "On · {where} · PostgreSQL {server}": "オン · {where} · PostgreSQL {server}",
  "{computers} computers · {sessions} sessions · {lessons} lessons · {audit} audit entries": "コンピューター {computers} 台 · セッション {sessions} 件 · ナレッジ {lessons} 件 · 監査ログ {audit} 件",
  "Keep what your team's computers share in a Postgres database as well, and send each computer that shares knowledge its teammates' lessons. Only this hub connects to the database; the other computers never get its address or password.": "チームの各コンピューターが共有したものを Postgres のデータベースにも残し、ナレッジを共有している各コンピューターにチームメイトのナレッジを返します。データベースにつなぐのはこのハブだけで、ほかのコンピューターはそのアドレスもパスワードも知りません。",
  "The Postgres driver isn't installed here. Run {command}, then restart the dashboard.": "このコンピューターには Postgres のドライバーが入っていません。{command} を実行してから、ダッシュボードを再起動してください。",
  "Team store": "チームストア",
  "Database {db} on {host}, as {user}": "{host} のデータベース {db}（ユーザー {user}）",
  "Change these settings on the hub itself, not from another device.": "この設定は、ほかのデバイスからではなく、ハブ自身で変更してください。",
  "Server address": "サーバーのアドレス",
  "Port": "ポート",
  "Database": "データベース",
  "User": "ユーザー",
  "Password": "パスワード",
  "saved; leave empty to keep it": "保存済み。空のままにすると変わりません",
  "SSL mode": "SSL モード",
  "Could not connect": "接続できませんでした",
  "Connected to {where} (PostgreSQL {server}).": "{where} に接続しました（PostgreSQL {server}）。",
  "The team store is there: {lessons} lessons from {computers} computers.": "チームストアがあります：コンピューター {computers} 台からのナレッジ {lessons} 件。",
  "Its tables are created when you save.": "保存すると、テーブルが作られます。",
  "This user can't create the team's tables here.": "このユーザーには、ここにチームのテーブルを作る権限がありません。",
  "Test connection": "接続をテスト",
  "Connecting and saving…": "接続して保存中…",
  "Could not save": "保存できませんでした",
  "Team store on: computers that share knowledge now get their teammates' lessons.": "チームストアをオンにしました。ナレッジを共有するコンピューターは、チームメイトのナレッジを受け取ります。",
  "Team store off. Its settings are kept.": "チームストアをオフにしました。設定は残してあります。",
  "Save": "保存",
  "Off": "オフ",
  "Saved in {file}, readable by your user only.": "{file} に保存され、あなたのユーザーだけが読めます。",
  "Sending to the hub": "ハブに送信",
  "Analyzed on the computer it ran on, which keeps its transcript": "実行したコンピューターで分析済み。トランスクリプトはそのコンピューターにあります",
  "transcript on {machine}": "トランスクリプトは {machine} に",
  "This session was analyzed on {machine}, which keeps its transcript. Only its summary and project lessons were shared.": "このセッションは {machine} で分析され、トランスクリプトはそちらにあります。共有されたのは要約とプロジェクトのナレッジだけです。",
  // Devices › people on a hub, the viewer, the sign-in screen
  "Only an admin of this hub can change this.": "これを変更できるのは、このハブの管理者だけです。",
  "Could not copy here: select the text and copy it yourself.": "ここではコピーできませんでした。テキストを選択して、ご自身でコピーしてください。",
  "Only an admin of this hub can change these settings.": "この設定を変更できるのは、このハブの管理者だけです。",
  "Opening the hub's dashboard without signing in: {error}": "サインインせずにハブのダッシュボードを開きます：{error}",
  "Invites people, changes roles and this hub's settings": "人を招待し、ロールとこのハブの設定を変更します",
  "Their computers send here and get teammates' lessons back": "コンピューターからここへ送り、チームメイトのナレッジを受け取ります",
  "Opens this dashboard; sends and changes nothing": "このダッシュボードを見るだけで、送信も変更もしません",
  "{browser} on {os}": "{os} の {browser}",
  "A browser": "ブラウザー",
  "Someone at the hub": "ハブのコンピューター",
  "someone": "だれか",
  "a computer": "コンピューター",
  "{actor} added {person} as {role}": "{actor} が {person} を{role}として追加",
  "{actor} changed {person}'s role from {before} to {after}": "{actor} が {person} のロールを{before}から{after}に変更",
  "{actor} removed {person}": "{actor} が {person} を削除",
  "{actor} made an invite for {person}": "{actor} が {person} の招待を作成",
  "{person} joined from {computer}": "{person} が {computer} から参加",
  "{person} signed in to the dashboard": "{person} がダッシュボードにサインイン",
  "{actor} revoked a computer or browser of {person}": "{actor} が {person} のコンピューターまたはブラウザーを取り消し",
  "{actor} changed which projects {person} sees": "{actor} が {person} に見えるプロジェクトを変更",
  "{actor} shared the project {path}": "{actor} がプロジェクト {path} を共有",
  "{actor} stopped sharing the project {path}": "{actor} がプロジェクト {path} の共有を停止",
  "Shared from this hub: its summaries and project lessons go to the people given it": "このハブから共有中：要約とプロジェクトの教訓が、このプロジェクトを割り当てた人に届きます",
  "Shared": "共有中",
  "Shared projects": "共有プロジェクト",
  "Stop sharing {name}? This computer's sessions there go back to their own folders and stop going to the team store. What others sent stays, and people keep it in their list until you change it.": "{name} の共有を停止しますか？ このコンピューターのセッションは元のフォルダーに戻り、チームストアに送られなくなります。ほかの人が送ったものは残り、各自の一覧からは変更するまで消えません。",
  "{name} is no longer shared.": "{name} の共有を停止しました。",
  "Stop sharing": "共有を停止",
  "no one limited to it yet": "まだ誰にも割り当てていません",
  "Seen by": "見える人",
  " · and {n} who see every project": " · ほかに、すべてのプロジェクトが見える {n} 人",
  "Sent from": "送信元",
  "Project to share": "共有するプロジェクト",
  "Share project": "プロジェクトを共有",
  "Search this hub's projects, or type a folder like ~/work/client-x": "このハブのプロジェクトを検索、またはフォルダーを入力（例: ~/work/client-x）",
  "Share the folder {path}": "フォルダー {path} を共有",
  "No project matches. Type a folder, starting with / or ~, to share it.": "一致するプロジェクトはありません。共有するには / か ~ で始まるフォルダーを入力してください。",
  "Pick a project from the list, or type its folder.": "一覧からプロジェクトを選ぶか、フォルダーを入力してください。",
  "{name} was already shared.": "{name} はすでに共有されています。",
  "Shared {name}: {n} sessions of this hub are in it. Give people access in People › Change.": "{name} を共有しました（このハブのセッション {n} 件）。人へのアクセスは「人」›「変更」で設定してください。",
  "Share another project": "ほかのプロジェクトを共有",
  "The folder and everything below it becomes one project. This computer's sessions there are filed under it, and other computers can add their own folder to it before anything was sent.": "そのフォルダーと配下のすべてが一つのプロジェクトになります。このコンピューターのそこでのセッションはこのプロジェクトに入り、ほかのコンピューターは何も送る前から自分のフォルダーを追加できます。",
  "Only these projects leave this computer: each analyzed session's summary and project lessons go to the team store and to the people given the project. Prompts, transcripts and every other project stay here.": "このコンピューターから出ていくのは、これらのプロジェクトだけです。分析済みセッションの要約とプロジェクトの教訓が、チームストアと、プロジェクトを割り当てた人に届きます。プロンプト、トランスクリプト、ほかのプロジェクトはすべてここに残ります。",
  "Only these projects leave this computer: people given them see each analyzed session's summary and project lessons on this hub's dashboard. Prompts, transcripts and every other project stay here.": "このコンピューターから出ていくのは、これらのプロジェクトだけです。割り当てた人は、分析済みセッションの要約とプロジェクトの教訓をこのハブのダッシュボードで見られます。プロンプト、トランスクリプト、ほかのプロジェクトはすべてここに残ります。",
  "No project is shared yet.": "共有中のプロジェクトはまだありません。",
  "Projects are shared, or stop being shared, at the hub computer itself: it decides what leaves it.": "プロジェクトの共有の開始と停止は、ハブのコンピューター自身で行います（何を外に出すかを決めるのはそのコンピューターです）。",
  "Every project": "すべてのプロジェクト",
  "No project yet": "プロジェクトなし",
  "set up, no sessions yet": "設定済み、セッションはまだありません",
  "Projects they see": "見えるプロジェクト",
  "Every project on this hub": "このハブのすべてのプロジェクト",
  "Search projects by name or folder": "名前かフォルダーでプロジェクトを検索",
  "No project matches “{q}”.": "「{q}」に一致するプロジェクトはありません。",
  "{n} chosen": "{n} 件選択",
  "Only these projects: their summaries and project lessons, never transcripts": "これらのプロジェクトだけ（要約とプロジェクトの教訓のみ。トランスクリプトは見えません）",
  "No projects yet: set one up on the hub with {command}.": "プロジェクトはまだありません。ハブで {command} を実行して設定してください。",
  "Change": "変更",
  "Cancel": "キャンセル",
  "{name} now sees: {projects}.": "{name} に見えるもの: {projects}",
  "Choose the projects they see, or every project.": "見えるプロジェクトを選ぶか、すべてのプロジェクトを選んでください。",
  "{name} will see no project on this hub. Save anyway?": "{name} にはこのハブのプロジェクトが何も見えなくなります。保存しますか？",
  "On this hub you see each session's summary and project lessons. Its transcript stays with whoever ran it.": "このハブでは各セッションの要約とプロジェクトの教訓が見えます。トランスクリプトはセッションを実行した人の手元に残ります。",
  "{actor} turned the shared hub token on": "{actor} がハブの共有トークンをオンに変更",
  "{actor} turned the shared hub token off": "{actor} がハブの共有トークンをオフに変更",
  "{actor} made this hub take knowledge only": "{actor} がこのハブをナレッジのみ受け付けるように変更",
  "{actor} let this hub take transcripts again": "{actor} がこのハブでトランスクリプトを再び受け付けるように変更",
  "Knowledge only": "ナレッジのみ",
  "Take knowledge only? Computers that send transcripts are turned away until they share knowledge only. Transcripts already here stay.": "ナレッジのみ受け付けますか？ トランスクリプトを送るコンピューターは、ナレッジのみの共有に切り替えるまで受け付けません。すでにあるトランスクリプトは残ります。",
  "This hub takes knowledge only now.": "このハブはナレッジのみ受け付けるようになりました。",
  "This hub takes transcripts again.": "このハブは再びトランスクリプトを受け付けます。",
  "On: every computer analyzes its own sessions and sends only summaries and project lessons. One that sends transcripts is turned away until it shares knowledge only.": "オン：どのコンピューターも自分のセッションを自分で分析し、要約とプロジェクトの教訓だけを送ります。トランスクリプトを送るコンピューターは、ナレッジのみの共有に切り替えるまで受け付けません。",
  "Off: computers may send their transcripts, which this hub records and analyzes, or share knowledge only. Turn it on to keep every transcript off this hub.": "オフ：コンピューターはトランスクリプトを送り、このハブで記録・分析することも、ナレッジのみを共有することもできます。トランスクリプトを一切このハブに置かないなら、オンにしてください。",
  "Run {command} on it, then {push}.": "そのコンピューターで {command} を実行してから、{push} を実行してください。",
  " · sends transcripts: turned away": " · トランスクリプトを送信：受け付けていません",
  "Invite for {name}": "{name} さんへの招待",
  "Shown once: copy what you need now. The code works once and expires {when}.": "表示はこの 1 回だけです。必要なものを今コピーしてください。コードは 1 回だけ使え、{when} に期限が切れます。",
  "Code": "コード",
  "To join their computer, they run": "コンピューターを参加させるには、相手が次を実行します",
  "Or, to open this dashboard in a browser": "または、ブラウザーでこのダッシュボードを開くには",
  "Send them one of these by chat or email: the hub sends nothing itself. A computer that joined can open this dashboard later without a code, from Settings › Devices.": "どちらかをチャットやメールで渡してください。ハブ自身は何も送りません。参加したコンピューターからは、あとで 設定 › デバイス からコードなしでこのダッシュボードを開けます。",
  "People": "利用者",
  "A computer": "コンピューター",
  "Stop {computer} from sending to this hub? It can join again only with a new invite.": "{computer} からこのハブへの送信を止めますか？ 再び参加するには新しい招待が必要です。",
  "End {name}'s dashboard session in {browser}? That browser has to sign in again.": "{browser} での {name} さんのダッシュボードのセッションを終了しますか？ そのブラウザーでは再びサインインが必要になります。",
  "Revoked.": "取り消しました。",
  "Revoke": "取り消す",
  "used {ago}": "最終使用 {ago}",
  "since {ago}": "{ago}から",
  "Role of {name}": "{name} さんのロール",
  "{name} is now: {role}.": "{name} さんのロールを{role}にしました。",
  "A new one-time code for another computer or browser": "別のコンピューターやブラウザー用に、1 回限りの新しいコードを作ります",
  "New invite": "新しい招待",
  "Remove {name} from this hub? Their computers stop sending and their dashboard sessions end at once. What they already sent stays here.": "{name} さんをこのハブから削除しますか？ そのコンピューターからの送信とダッシュボードのセッションは、すぐに止まります。すでに送られたものはここに残ります。",
  "{name} was removed.": "{name} さんを削除しました。",
  " (you)": "（あなた）",
  "Invite open until {when}": "招待は {when} まで有効",
  "Not joined yet": "まだ参加していません",
  "No computer or browser yet: make a new invite": "コンピューターもブラウザーもまだありません。新しい招待を作ってください",
  "optional": "任意",
  "Create invite": "招待を作成",
  "Name": "名前",
  "Email": "メール",
  "Role": "ロール",
  "Invite someone": "招待する",
  "Email is optional; it lets a company sign-in in front of the hub recognize the person.": "メールは任意です。ハブの前に会社のサインインを置く場合に、その人を見分けるために使います。",
  "Shared hub token": "ハブの共有トークン",
  "Turn off the shared hub token? Computers that joined with it stop sending until someone joins them again with an invite.": "ハブの共有トークンをオフにしますか？ これで参加したコンピューターは、招待で参加し直すまで送信できなくなります。",
  "Computers with the shared hub token can send again.": "共有トークンを持つコンピューターも、再び送信できます。",
  "Only computers that joined with an invite can send now.": "これからは、招待で参加したコンピューターだけが送信できます。",
  "On: computers that joined with the hub's shared token, before there were people, can still send. Turn it off once everyone has joined with their own invite.": "オン：利用者を追加する前にハブの共有トークンで参加したコンピューターも、引き続き送信できます。全員が自分の招待で参加したら、オフにしてください。",
  "Off: only computers that joined with a person's invite can send. Computers that joined with the shared token are turned away.": "オフ：利用者の招待で参加したコンピューターだけが送信できます。共有トークンで参加したコンピューターは受け付けません。",
  "Recent changes": "最近の変更",
  "{n} person": "{n} 人",
  "{n} people": "{n} 人",
  "Person": "利用者",
  "Computers and browsers": "コンピューターとブラウザー",
  "Admins invite people and change this hub's settings; members' computers send here and get their teammates' lessons back; read-only people only open this dashboard. Whoever is at this computer is always an admin.": "管理者は人を招待し、このハブの設定を変更します。メンバーのコンピューターはここへ送り、チームメイトのナレッジを受け取ります。閲覧のみの人は、このダッシュボードを見るだけです。このコンピューターの前にいる人は、常に管理者です。",
  "Give each person a role: admins invite people and change this hub's settings, members' computers send here and get their teammates' lessons back, and read-only people only open this dashboard. The first person you add as admin can manage the hub from their own computer.": "一人ひとりにロールを与えます。管理者は人を招待してこのハブの設定を変更し、メンバーのコンピューターはここへ送ってチームメイトのナレッジを受け取り、閲覧のみの人はこのダッシュボードを見るだけです。最初に管理者として追加した人は、自分のコンピューターからハブを管理できます。",
  "Until you add someone, nothing changes: computers send with the hub's shared token, as they do now.": "だれかを追加するまでは何も変わりません。コンピューターはこれまでどおり、ハブの共有トークンで送信します。",
  "This hub has no address set, so invites use the one this page was opened with ({host}). Set the address others reach it at with {command}.": "このハブにはアドレスが設定されていないため、招待にはこのページを開いたアドレス（{host}）を使います。ほかの人がハブにつなぐアドレスは {command} で設定します。",
  "Admin": "管理者",
  "Member": "メンバー",
  "Read-only": "閲覧のみ",
  "Sign out": "サインアウト",
  "Invite code": "招待コード",
  "Sign in": "サインイン",
  "Sign in to this hub": "このハブにサインイン",
  "This hub's dashboard opens only for people an admin has added. There is no password: you sign in from your own Chronicle, or with an invite code.": "このハブのダッシュボードは、管理者が追加した人だけが開けます。パスワードはありません。自分の Chronicle から、または招待コードでサインインします。",
  "From your own computer": "自分のコンピューターから",
  "If your computer already sends to this hub, open Chronicle there and choose {path}.": "あなたのコンピューターがすでにこのハブに送信しているなら、そこで Chronicle を開き、{path} を選びます。",
  "With an invite code": "招待コードで",
  "A code works once. No code, or it has expired? Ask an admin of this hub for a new one.": "コードは 1 回だけ使えます。コードがない、または期限が切れている場合は、このハブの管理者に新しいコードを頼んでください。",
  // Team Home and the Team section of a hub
  "{name} hasn't joined yet. The invite is open until {date}.": "{name} さんはまだ参加していません。招待は {date} まで有効です。",
  "{name} has no computer or browser signed in, and no open invite. Make them a new one.": "{name} さんにはサインイン中のコンピューターもブラウザーも、有効な招待もありません。新しい招待を作ってください。",
  "{computer} was last heard from {ago}.": "{computer} からの最後の連絡は {ago}です。",
  "{computer} hasn't been heard from yet.": "{computer} からはまだ連絡がありません。",
  "Needs attention": "要対応",
  "Team": "チーム",
  "Your projects on this hub, {period}": "このハブのあなたのプロジェクト（{period}）",
  "The team's projects on this hub, {period}": "このハブのチームのプロジェクト（{period}）",
  "{n}d": "{n} 日",
  "Team overview": "チームの概要",
  "No team projects yet": "チームのプロジェクトはまだありません",
  "No project on this hub is shared with you yet. Ask an admin of this hub.": "このハブで、あなたに共有されているプロジェクトはまだありません。このハブの管理者に頼んでください。",
  "A project shows up here once it is set up on the hub with {command}, or another computer sends sessions to it. Projects only this computer works on stay under {activity}.": "ハブで {command} を実行して設定するか、ほかのコンピューターがセッションを送ると、プロジェクトがここに表示されます。このコンピューターだけで作業しているプロジェクトは {activity} に表示されます。",
  "New lessons": "新しい教訓",
  "People active": "活動した人",
  "of {n} on this hub": "このハブの {n} 人中",
  "Projects active": "動きのあったプロジェクト",
  "of {n} team projects": "チームの {n} プロジェクト中",
  "of {n} team project": "チームの {n} プロジェクト中",
  "Team projects": "チームのプロジェクト",
  "sessions and new lessons, {period}": "セッションと新しい教訓（{period}）",
  "Lessons": "教訓",
  "Who": "メンバー",
  "Latest": "最新",
  "no sessions yet": "セッションはまだありません",
  "Who worked on what": "誰が何に取り組んだか",
  "Nobody worked on a team project in {period}.": "{period}、チームのプロジェクトで作業した人はいません。",
  "Open the session it came from": "元のセッションを開く",
  "No lessons from team projects yet. Sessions are analyzed automatically once idle.": "チームのプロジェクトの教訓はまだありません。セッションはアイドルになると自動で分析されます。",
  "This computer is the hub. Its people, shared projects, computers and team store are under Team.": "このコンピューターはハブです。利用者、共有プロジェクト、コンピューター、チームストアは「チーム」にあります。",
  "Only an admin of this hub sees them.": "これらを見られるのは、このハブの管理者だけです。",
  "Last heard from {ago}": "最終連絡 {ago}",
  "Only an admin of this hub can see this.": "これを見られるのは、このハブの管理者だけです。",
  "This computer isn't a hub, so it has no team. {page} says how to make it one.": "このコンピューターはハブではないため、チームはありません。ハブにする方法は {page} にあります。",
  "Who may send to this hub and open its dashboard, with which role and projects.": "このハブに送信し、ダッシュボードを開けるのはだれか。それぞれのロールとプロジェクト。",
  "Projects set up on this hub: who sees each, and which computers send to it.": "このハブで設定したプロジェクト。それぞれを見られる人と、送信するコンピューター。",
  "This hub's projects: who sees each, and which computers send to it. Make one here, then each computer adds its folder to it.": "このハブのプロジェクト。それぞれを見られる人と、送信するコンピューター。ここで作成し、各コンピューターがフォルダーを加えます。",
  "Remove {name} from this hub's projects? What computers already sent stays filed under it, and people keep it in their list until you change it.": "{name} をこのハブのプロジェクトから外しますか？コンピューターがすでに送ったものはそのまま残り、利用者の一覧にも変更するまで残ります。",
  "{name} was removed from this hub's projects.": "{name} をこのハブのプロジェクトから外しました。",
  "Project name, e.g. Website": "プロジェクト名（例：Website）",
  "Project name": "プロジェクト名",
  "Create project": "プロジェクトを作成",
  "{name} already exists.": "{name} はすでにあります。",
  "Created {name}. Give people access in People, and have each computer add its folder to it.": "{name} を作成しました。People で利用者に見られるようにし、各コンピューターにフォルダーを加えてもらってください。",
  "New project": "新しいプロジェクト",
  "A project shows up here once an admin makes it in {projects}, or a computer sends sessions to it.": "プロジェクトは、管理者が {projects} で作成するか、コンピューターがセッションを送るとここに表示されます。",
  "Team › Projects": "チーム › プロジェクト",
  "Each computer adds its own folder for the project with {command}. Once one computer has sent sessions from a git repository, other clones of it go there on their own.": "各コンピューターは {command} でプロジェクトに自分のフォルダーを加えます。あるコンピューターが git リポジトリのセッションを送ると、同じリポジトリのほかのクローンは自動でそこに入ります。",
  "Each computer sends a project's analyzed sessions here as summaries and project lessons, never prompts or transcripts. Only the people given the project see them.": "各コンピューターは、プロジェクトの分析済みセッションを要約とプロジェクトのナレッジとしてここに送ります。プロンプトやトランスクリプトは送りません。見られるのは、そのプロジェクトを割り当てられた人だけです。",
  "No project yet.": "プロジェクトはまだありません。",
  "Every computer this hub hears from, and whose it is.": "このハブにつながるすべてのコンピューターと、その持ち主。",
  "The team's record in Postgres, which only this hub connects to.": "Postgres に置くチームの記録。接続するのはこのハブだけです。",
  "team projects": "チームのプロジェクト",
  "team": "チーム",
  "This is the hub {name}": "ハブ {name} です",
  "The team's hub: computers send what they learn here": "チームのハブ：各コンピューターが学んだことをここに送ります",
  "A hub: other computers send what they learn here": "ハブ：ほかのコンピューターが学んだことをここに送ります",
  "Hub": "ハブ",
  "System map": "システムマップ",
  "Ways in": "入口",
  "Data": "データ",
  "Delivery": "デリバリー",
  "Runs on & uses": "実行先と利用先",
  "UI": "UI",
  "API": "API",
  "Command line": "コマンドライン",
  "Extension": "拡張機能",
  "Desktop app": "デスクトップアプリ",
  "MCP server": "MCP サーバー",
  "Worker": "ワーカー",
  "Service": "サービス",
  "Package": "パッケージ",
  "Folder": "フォルダー",
  "Data store": "データストア",
  "CI": "CI",
  "Infrastructure": "インフラ",
  "Container image": "コンテナイメージ",
  "Deployed": "デプロイ先",
  "Server": "サーバー",
  "Platform": "プラットフォーム",
  "External service": "外部サービス",
  "mentioned in its glossary": "用語集で言及",
  "not on this computer": "このコンピューターにはありません",
  "{n} part": "{n} 個のパーツ",
  "{n} parts": "{n} 個のパーツ",
  "runs as {names}": "実行先：{names}",
  "files": "ファイル",
  "glossary": "用語集",
  "Built with": "使用技術",
  "Runs on": "実行先",
  "Uses": "利用先",
  "Other systems · {n}": "ほかのシステム · {n}",
  "Open system": "システムを開く",
  "Project page": "プロジェクトページ",
  "Your systems": "あなたのシステム",
  "Every folder your agents worked in, grouped by where it lives. Parts and links come from evidence only: the manifests in each project and what sessions did there.": "エージェントが作業したすべてのフォルダーを、置き場所ごとにまとめています。パーツとつながりは根拠からだけ描きます：各プロジェクトのマニフェストと、そこでセッションが行ったことです。",
  "systems": "システム",
  "link": "つながり",
  "links": "つながり",
  "{n} one-session folders hidden": "セッションが 1 つだけのフォルダー {n} 件を非表示",
  "Links": "つながり",
  "sessions in one project edited or read files of another": "あるプロジェクトのセッションが、別のプロジェクトのファイルを編集または読み込んだ",
  "its glossary says how it uses the other": "用語集に、もう一方をどう使うかが書かれている",
  "Most active": "活動が多い順",
  "Click a system for its summary, double-click to open it. Drag to move, pinch or ⌘-scroll to zoom.": "システムをクリックすると概要、ダブルクリックで開きます。ドラッグで移動、ピンチまたは ⌘ + スクロールでズームします。",
  "Manifests are not read ([systems] read_manifests = false): parts come from sessions only.": "マニフェストは読み込んでいません（[systems] read_manifests = false）。パーツはセッションからだけ描いています。",
  "Find systems…": "システムを検索…",
  "Find systems by name, stack or where they run": "名前、技術スタック、実行先でシステムを検索",
  "Systems": "システム",
  "{systems} systems in {groups} folders, and how they connect": "{groups} 個のフォルダーにある {systems} 個のシステムと、そのつながり",
  "One-session folders": "セッション 1 つのフォルダー",
  "No systems yet: they appear once sessions are recorded in project folders.": "まだシステムはありません。プロジェクトフォルダーでセッションが記録されると表示されます。",
  "No such system.": "そのシステムは見つかりません。",
  "All systems": "すべてのシステム",
  "{n} session edited or read files here": "{n} セッションがここのファイルを編集または読み込み",
  "{n} sessions edited or read files here": "{n} セッションがここのファイルを編集または読み込み",
  "edit": "編集",
  "edits": "編集",
  "Ports": "ポート",
  "agents called it at {paths}": "エージェントが呼び出したパス：{paths}",
  "Connections": "つながり",
  "Why it is here": "ここにある理由",
  "Click a part to see why it is here: the manifest lines and commands behind it.": "パーツをクリックすると、それがここにある理由（根拠になったマニフェストの行とコマンド）を表示します。",
  "Also runs on": "ほかの実行先",
  "Where sessions worked": "セッションが作業した場所",
  "Other ports seen": "そのほかに見つかったポート",
  "{n} part of its own": "自前のパーツ {n} 個",
  "{n} parts of its own": "自前のパーツ {n} 個",
  "{n} thing it ships to, stores in or uses": "デプロイ先・保存先・利用先 {n} 個",
  "{n} things it ships to, stores in or uses": "デプロイ先・保存先・利用先 {n} 個",
  "{n} connection": "{n} 本のつながり",
  "{n} connections": "{n} 本のつながり",
  "Nothing to draw yet: no manifests were read and sessions left no trace of parts.": "まだ描けるものがありません。マニフェストを読み込んでおらず、セッションにもパーツの手がかりがありません。",
  "Systems map": "システムマップ",
  "every project, its parts and links": "すべてのプロジェクトと、そのパーツとつながり",
  "calls [edge]": "呼び出す",
  "depends on": "依存",
  "uses": "利用",
  "stores in": "保存",
  "deploys to": "デプロイ",
  "deployed as": "デプロイ先",
  "runs on": "実行",
  "provisions": "作成",
  "calls {path}": "{path} を呼び出す",
  "reached in {n} command": "{n} 件のコマンドでアクセス",
  "reached in {n} commands": "{n} 件のコマンドでアクセス",
  "{tool} in {n} command": "{n} 件のコマンドで {tool}",
  "{tool} in {n} commands": "{n} 件のコマンドで {tool}",
  "started on :{port} in {n} command": "{n} 件のコマンドで :{port} で起動",
  "started on :{port} in {n} commands": "{n} 件のコマンドで :{port} で起動",
  "Only {name}'s": "{name} のものだけ",
  "Everyone": "全員",
  "Someone not listed": "一覧にない人",
  "API provider": "API プロバイダー",
  "Provider": "プロバイダー",
  "in use": "使用中",
  "AWS region": "AWS リージョン",
  "AWS profile": "AWS プロファイル",
  "Resource name": "リソース名",
  "Endpoint": "エンドポイント",
  "deployment name": "デプロイ名",
  "Small model (screening)": "小さいモデル（選別用）",
  "same as Model": "モデルと同じ",
  "Context window (tokens)": "コンテキスト長（トークン）",
  "Characters per call": "1 回あたりの文字数",
  "stored; type to replace it": "保存済み。入力すると置き換えます",
  "from {variable}": "{variable} から",
  "optional: without one, your AWS sign-in is used": "任意：なければ AWS のサインインを使います",
  "optional: without one, your az login is used": "任意：なければ az login のサインインを使います",
  "required": "必須",
  "API key ({variable})": "API キー（{variable}）",
  "API key": "API キー",
  "{provider} settings saved.": "{provider} の設定を保存しました。",
  "Saving and asking {provider}…": "保存して {provider} に問い合わせています…",
  "The model answered, but not as asked.": "モデルは応答しましたが、指示どおりの形ではありませんでした。",
  "Works: {model} answered in {seconds}s.": "接続できました：{model} が {seconds} 秒で応答しました。",
  "In use": "使用中",
  "Use for analysis": "分析に使う",
  "API key removed.": "API キーを削除しました。",
  "Remove key": "キーを削除",
  "Runs on this computer: transcripts never leave it.": "このコンピューター上で動きます：トランスクリプトは外に出ません。",
  "Ready": "準備完了",
  "Not set up": "未設定",
  "Sends a redacted digest of each session to {host}.": "各セッションの秘匿化したダイジェストを {host} に送ります。",
  "Advanced": "詳細設定",
  "Saved in config.toml under {section}. The key goes in provider-keys.json, which only you can read.": "設定は config.toml の {section} に保存されます。キーは provider-keys.json に入り、あなただけが読めます。",
  "Queue": "分析待ち",
  "held": "保留",
  "Sessions: ": "セッション：",
  "spent": "使用額",
  "API-equivalent: what the tokens would cost at list prices": "API 換算：トークンを定価で払った場合の金額",
  "Effort": "推論の深さ",
  "Model (sessions)": "モデル（セッション）",
  "Knowledge bases": "ナレッジベース",
  "Codex's default": "Codex の既定",
  "Runs Bob Shell headless (bob run) with no tools and Bob's own model; only a redacted digest of each session is sent.": "Bob Shell をヘッドレス（bob run）で、ツールなし・Bob 自身のモデルで実行します。送るのは各セッションの秘匿化したダイジェストだけです。",
  "Bob keeps each analysis in its own task list; Chronicle doesn't record them as sessions.": "Bob は各分析を自身のタスク一覧に残します。Chronicle はそれをセッションとして記録しません。",
  "Share the summaries and project lessons of sessions in every folder on this computer, including projects the hub doesn't have?": "このコンピューターのすべてのフォルダーのセッションについて、要約とプロジェクトのナレッジを共有しますか？ハブにないプロジェクトも含まれます。",
  "This computer now shares sessions from every folder.": "このコンピューターはすべてのフォルダーのセッションを共有します。",
  "This computer now shares only sessions in the hub's projects.": "このコンピューターはハブのプロジェクトのセッションだけを共有します。",
  "The hub's projects": "ハブのプロジェクト",
  "Every folder": "すべてのフォルダー",
  // Devices on a computer that sends to a hub (its projects there), Team › Hub settings
  "Share now": "今すぐ共有",
  "Leave the hub at {host}? This computer stops sending to it, and records and analyzes its own sessions again. The hub keeps what it was sent. Joining again takes a new invite.": "{host} のハブから抜けますか？このコンピューターはハブへの送信をやめ、自分のセッションを再び自分で記録・分析します。ハブは送られたものを残します。再び参加するには新しい招待が必要です。",
  "This computer left the hub.": "このコンピューターはハブから抜けました。",
  "Leave the hub…": "ハブから抜ける…",
  "Nothing sent yet": "まだ何も送っていません",
  "Last send had problems": "前回の送信で問題がありました",
  "last shared": "前回の共有",
  "last sent": "前回の送信",
  "sessions shared": "共有したセッション",
  "files sent": "送ったファイル",
  "kept here": "ここに残したもの",
  "teammates' lessons": "チームメイトのナレッジ",
  "Teammates' lessons are read-only here: your MCP tools answer with them, and the start-of-session notes list them as teammates'.": "チームメイトのナレッジはここでは読み取り専用です。MCP ツールはそれも答えに使い、セッション開始時のメモにもチームメイトのものとして並びます。",
  "No teammates' lessons yet: a hub with a team store sends them back after each share.": "チームメイトのナレッジはまだありません。チームストアを持つハブが、共有のたびに送り返します。",
  "The folder {path}": "フォルダー {path}",
  "Nothing matches. Type a folder, starting with / or ~.": "一致するものがありません。/ か ~ で始まるフォルダーを入力してください。",
  "For a folder added by mistake": "間違えて追加したフォルダー用",
  "Remove {folder} from {name}? Its sessions stop going there, and the hub deletes what this computer shared from it, with the lessons. Only for a folder added by mistake: to keep what you shared, leave the project instead.": "{folder} を {name} から外しますか？そのセッションは送られなくなり、このコンピューターがそこから共有したものはナレッジごとハブから削除されます。間違えて追加したフォルダーのためのものです。共有したものを残すなら、プロジェクトから抜けてください。",
  "Remove {folder} from {name}? The hub files its sessions by their git remote or their own folder again.": "{folder} を {name} から外しますか？ハブはそのセッションを、git リモートか元のフォルダーで振り分け直します。",
  "{folder} no longer goes to {name}.": "{folder} はもう {name} に送られません。",
  "Removed. The hub deleted the {n} session this computer shared from there.": "外しました。このコンピューターがそこから共有した {n} 件のセッションをハブが削除しました。",
  "Removed. The hub deleted the {n} sessions this computer shared from there.": "外しました。このコンピューターがそこから共有した {n} 件のセッションをハブが削除しました。",
  "Leave {name}? This computer stops sharing its sessions there and stops getting its teammates' lessons. What it already shared stays on the hub.": "{name} から抜けますか？このコンピューターはそこへのセッションの共有と、チームメイトのナレッジの受け取りをやめます。すでに共有したものはハブに残ります。",
  "Rejoined {name}: its sessions are shared again.": "{name} に再参加しました。セッションが再び共有されます。",
  "Left {name}. What this computer shared there stays on the hub.": "{name} から抜けました。このコンピューターがそこで共有したものはハブに残ります。",
  "Rejoin": "再参加",
  "Leave": "抜ける",
  "This computer no longer shares here or gets its lessons. What it shared stays on the hub.": "このコンピューターはここへの共有も、ナレッジの受け取りもしていません。共有したものはハブに残っています。",
  "Left": "抜けました",
  "not shared yet": "まだ共有していません",
  "{n} session shared": "{n} 件のセッションを共有",
  "{n} sessions shared": "{n} 件のセッションを共有",
  "by its git remote {remote}": "git リモート {remote} で",
  "No folder here goes to it now.": "いまはここのどのフォルダーもこのプロジェクトに送られていません。",
  "Asking the hub for its projects…": "ハブにプロジェクトを問い合わせ中…",
  "Project on the hub": "ハブのプロジェクト",
  "Search the hub's projects": "ハブのプロジェクトを検索",
  "Folder on this computer": "このコンピューターのフォルダー",
  "Search your folders, or type one like ~/code/app": "フォルダーを検索するか、~/code/app のように入力",
  "Join": "参加",
  "Pick one of the hub's projects.": "ハブのプロジェクトを選んでください。",
  "Pick a folder, or type its full path.": "フォルダーを選ぶか、フルパスを入力してください。",
  "Its sessions already go to {name}: the hub knows its git remote ({remote}).": "そのセッションはすでに {name} に送られています。ハブがその git リモート（{remote}）を知っています。",
  "Sessions in {folder} now go to {name}.": "{folder} のセッションは {name} に送られるようになりました。",
  "Pick the project, then the folder here that holds it. Sessions in that folder and the folders below it are shared there, and its teammates' lessons come back.": "プロジェクトを選び、次にそれが入っているこのコンピューターのフォルダーを選んでください。そのフォルダーとその下のフォルダーのセッションがそこに共有され、チームメイトのナレッジが返ってきます。",
  "Join a project": "プロジェクトに参加",
  "Projects on the hub": "ハブのプロジェクト",
  "This computer isn't in any of the hub's projects yet. Join one to share its sessions there and get its teammates' lessons.": "このコンピューターはまだハブのどのプロジェクトにも参加していません。参加すると、そこにセッションを共有し、チームメイトのナレッジを受け取ります。",
  "Leaving a project keeps what this computer shared there. Remove is for a folder added by mistake: the hub deletes what it shared from it.": "プロジェクトから抜けても、このコンピューターがそこで共有したものは残ります。「外す」は間違えて追加したフォルダー用で、そこから共有したものをハブが削除します。",
  "What this computer shares": "このコンピューターが共有するもの",
  "What it sends": "送るもの",
  "Analyzed here with your own login. The hub gets each session's summary and project lessons; transcripts and lessons about you stay here.": "自分のログインでここで分析します。ハブには各セッションの要約とプロジェクトのナレッジが届き、トランスクリプトとあなたについてのナレッジはここに残ります。",
  "The hub records and analyzes the transcripts; this computer no longer analyzes its own sessions. This dashboard shows what it had before it joined.": "トランスクリプトはハブが記録・分析し、このコンピューターは自分のセッションを分析しなくなります。このダッシュボードには参加前のものが表示されます。",
  "Which sessions": "対象のセッション",
  "Every folder's, including projects the hub doesn't have.": "すべてのフォルダーのセッション。ハブにないプロジェクトも含みます。",
  "Only those in the hub's projects: the folders above, and repositories whose git remote the hub knows. The rest stay here.": "ハブのプロジェクトのセッションだけ：上のフォルダーと、ハブが git リモートを知っているリポジトリ。それ以外はここに残ります。",
  "{computer} left the project {project}": "{computer} がプロジェクト {project} から抜けました",
  "{computer} rejoined the project {project}": "{computer} がプロジェクト {project} に再参加しました",
  "{computer} took back {n} session it shared to {project}": "{computer} が {project} に共有したセッション {n} 件を取り消しました",
  "{computer} took back {n} sessions it shared to {project}": "{computer} が {project} に共有したセッション {n} 件を取り消しました",
  "{actor} purged {n} session": "{actor} がセッション {n} 件を完全に削除しました",
  "{actor} purged {n} sessions": "{actor} がセッション {n} 件を完全に削除しました",
  "{actor} set this hub's address to {address}": "{actor} がこのハブのアドレスを {address} にしました",
  "{actor} renamed this hub to {name}": "{actor} がこのハブの名前を {name} に変えました",
  "this computer's name": "このコンピューターの名前",
  "Hub settings": "ハブの設定",
  "It no longer shares here or gets this project's lessons. What it shared stays.": "ここへの共有も、このプロジェクトのナレッジの受け取りもやめています。共有したものは残ります。",
  " (left)": "（抜けました）",
  "name, address, backups": "名前、アドレス、バックアップ",
  "Set by {name} in the hub's .env: change it there, then run {command}.": "ハブの .env の {name} で決まります。そちらで変更してから {command} を実行してください。",
  "This computer isn't a hub, so it has no hub settings. {page} says how to make it one.": "このコンピューターはハブではないので、ハブの設定はありません。ハブにする方法は {page} にあります。",
  "This hub": "このハブ",
  "Shown in the band at the top of every page, in invites and on members' computers.": "各ページ上部の帯、招待、メンバーのコンピューターに表示されます。",
  "The hub's name is saved.": "ハブの名前を保存しました。",
  "Address": "アドレス",
  "Where computers and browsers reach this hub. Invites and sign-in links use it.": "コンピューターとブラウザーがこのハブにつなぐ場所です。招待とサインインのリンクに使われます。",
  "The hub's address is saved. New invites use it.": "ハブのアドレスを保存しました。新しい招待はこのアドレスを使います。",
  "Computers analyze their own sessions. This hub's model writes each project's knowledge base from the lessons they share, so it needs one to have knowledge bases.": "各コンピューターが自分のセッションを分析します。このハブのモデルは、共有されたナレッジから各プロジェクトのナレッジベースを書くので、ナレッジベースにはモデルが必要です。",
  "This hub's model analyzes the transcripts computers send, and writes each project's knowledge base.": "このハブのモデルが、送られてきたトランスクリプトを分析し、各プロジェクトのナレッジベースを書きます。",
  "Copy the database while the hub runs, then download the copy. Run these where the hub's compose.yaml is:": "ハブが動いたままデータベースをコピーし、そのコピーをダウンロードします。ハブの compose.yaml があるところで実行してください：",
  "And the team store:": "チームストアも：",
  "Copy the database while the hub runs:": "ハブが動いたままデータベースをコピーします：",
  "Back up the team store's Postgres database with your usual tools, such as pg_dump.": "チームストアの Postgres データベースは、pg_dump など普段のツールでバックアップしてください。",
  "Back up": "バックアップ",
  "Never copy chronicle.db itself while the hub runs: the copy can be corrupted.": "ハブの動作中に chronicle.db そのものをコピーしないでください。コピーが壊れることがあります。",
  "What this hub is called, where it's reached, and how it's kept.": "このハブの名前、つなぐ場所、保守の方法。",
  // Your own groups of projects
  "Other projects": "その他のプロジェクト",
  "All of {group}": "{group} のすべて",
  "Move to a group": "グループへ移動",
  "Move {name} to a group": "{name} をグループへ移動",
  "In it by its folder": "フォルダーのルールで所属",
  "In it now": "現在の所属",
  "No group": "グループなし",
  "New group…": "新しいグループ…",
  "Starting with {name}": "{name} から始める",
  "e.g. Aktio": "例：Aktio",
  "Add a folder, e.g. ~/Projects/Work/Aktio": "フォルダーを追加（例：~/Projects/Work/Aktio）",
  "Add a folder": "フォルダーを追加",
  "Remove the rule {folder}": "ルール {folder} を削除",
  "No folder rule: only the projects ticked below.": "フォルダーのルールはありません。下でチェックしたプロジェクトだけが入ります。",
  "Suggested from the projects you picked.": "選んだプロジェクトから提案しています。",
  "by folder": "フォルダー",
  "in {group}": "{group} に所属",
  "{n} project in this group": "このグループに {n} プロジェクト",
  "{n} projects in this group": "このグループに {n} プロジェクト",
  "Saved {name}.": "{name} を保存しました。",
  "Made the group {name}.": "グループ {name} を作りました。",
  "Delete {name}? Its projects stay": "{name} を削除しますか？プロジェクトは残ります",
  "Deleted the group {name}. Its projects are still here.": "グループ {name} を削除しました。プロジェクトはそのまま残っています。",
  "Delete group": "グループを削除",
  "Edit group": "グループを編集",
  "New group": "新しいグループ",
  "Folder rules": "フォルダーのルール",
  "New projects under these folders join the group on their own.": "これらのフォルダーの下にできた新しいプロジェクトは、自動でこのグループに入ります。",
  "Make group": "グループを作る",
  "Edit": "編集",
  "No projects in this group yet.": "このグループにはまだプロジェクトがありません。",
  "{projects} in {groups}": "{projects}（{groups}）",
  // Projects on the hub
  "Set up on the hub: no sessions yet": "ハブで設定済み：まだセッションがありません",
  "In {name} on the hub: what it shares goes there, and teammates' lessons come back here": "ハブの {name} に所属：共有するものはそこへ送られ、チームメイトの教訓がここに戻ります",
  "On the hub": "ハブ",
  "On the hub as {name}": "ハブでは {name}",
  "Shared from this hub": "このハブから共有中",
  "{name} on {hub}": "{hub} の {name}",
  "{n} session from the team": "チームのセッション {n} 件",
  "{n} sessions from the team": "チームのセッション {n} 件",
  "Opens on the hub in a new tab": "ハブを新しいタブで開きます",
  "The projects on {hub} that this computer's folders go to": "このコンピューターのフォルダーの送り先になっている {hub} のプロジェクト",
  "Open on the hub": "ハブで開く",
  // A group shared as one project on the hub
  "Share on the hub": "ハブで共有",
  "Not shared": "共有しない",
  "No projects on the hub yet, as of the last push. Make one there, or join one in Settings › Devices.": "最後に送ったときの時点で、ハブにはまだプロジェクトがありません。ハブで作るか、Settings › Devices で参加してください。",
  "From the next push, its {n} project goes to {name} on the hub, and so does any project that joins the group later. One that leaves it stops going; what it shared stays.": "次に送るときから、この {n} プロジェクトはハブの {name} に送られます。あとからグループに入るプロジェクトも同じです。グループから外れたものは送られなくなり、共有済みのものは残ります。",
  "From the next push, its {n} projects go to {name} on the hub, and so does any project that joins the group later. One that leaves it stops going; what it shared stays.": "次に送るときから、この {n} プロジェクトはハブの {name} に送られます。あとからグループに入るプロジェクトも同じです。グループから外れたものは送られなくなり、共有済みのものは残ります。",
  "Stops sharing from the next push. What it shared stays on the hub.": "次に送るときから共有をやめます。共有済みのものはハブに残ります。",
  "Its projects go to the hub only as they would without the group.": "プロジェクトは、グループがない場合と同じようにハブに送られます。",
  "Not from here, being recorded on another computer: {names}": "別のコンピューターで記録されたため、ここからは送られません：{names}",
  "Saved {name}. It goes to {project} on the hub from the next push.": "{name} を保存しました。次に送るときから、ハブの {project} に送られます。",
  "Saved {name}. It stops sharing from the next push; what it shared stays on the hub.": "{name} を保存しました。次に送るときから共有をやめます。共有済みのものはハブに残ります。",
  "Share the whole group as one project there": "グループ全体を、ハブの 1 つのプロジェクトとして共有します",
  "Every project in this group goes to {name} on the hub, including ones that join it later": "このグループのすべてのプロジェクトがハブの {name} に送られます。あとから入るものも含みます",
  "your group, with every project in it": "あなたのグループ（中のすべてのプロジェクト）",
  "from {names}": "{names} から",
  "from teammates": "チームメイトから",
  "From teammates": "チームメイトから",
  "A teammate's lesson, sent back by the team hub. Your agent gets it too.": "チームのハブから届いた、チームメイトのナレッジです。あなたのエージェントにも渡ります。",
  "Read them": "見る",
  // Team overview: what other computers sent (news.py)
  "New since your last visit": "前回からの新着",
  "{n} update": "{n} 件の更新",
  "{n} updates": "{n} 件の更新",
  "{n} update from the team: see Team overview": "チームから {n} 件の更新があります。チームの概要で確認できます",
  "{n} updates from the team: see Team overview": "チームから {n} 件の更新があります。チームの概要で確認できます",
  "Team overview, {n} new": "チームの概要（新着 {n} 件）",
  "{computer} joined the hub as {name}": "{computer} が {name} としてハブに参加しました",
  "{computer} joined the hub": "{computer} がハブに参加しました",
  "{n} lesson": "{n} 件の教訓",
  "{n} lessons": "{n} 件の教訓",
  "New from {who} in {project}: {what}": "{project} に {who} から新着: {what}",
  // Learning cases and private work notes
  "What your sessions taught you, and how to put it to use": "セッションから得た学びと、その活かし方",
  "Learn from your work": "仕事から学ぶ",
  "Explore every lesson by category, with diagrams and ready-to-use explanations.": "すべての学びを分野ごとに探索。図解と、そのまま活かせる解説付きです。",
  "Browser storage is unavailable. Learning history and notes last for this tab.": "ブラウザーに保存できません。学習履歴とメモは、このタブを開いている間だけ保持されます。",
  "Source and lesson trust": "出典とナレッジの信頼性",
  "Explanation": "説明",
  "Checks for next time": "次回の確認事項",
  "Principle": "原則",
  "Source": "出典",
  "No lessons yet": "学びはまだありません",
  "Saved work notes": "保存した作業メモ",
  "Your work, organized into lessons. Explore any category, anytime.": "仕事から得た学びを分野ごとに整理。いつでも自由に読むことができます。",
  "Learning views": "学習の表示",
  "Lesson library": "学びのライブラリー",
  "Reading history and work notes stay in this browser.": "読んだ履歴と作業メモは、このブラウザーに保存されます。",
  "Look at the evidence": "根拠を見る",
  "Next lesson": "次の学び",
  "Revisit sooner": "早めに復習",
  "Work note saved": "作業メモを保存済み",
  "Work note saved in this browser": "作業メモをこのブラウザーに保存しました",
  "Work note kept for this tab": "作業メモをこのタブで保持しています",
  "Save work note": "作業メモを保存",
  "The principle to keep": "覚えておきたい原則",
  "Use it in your next task": "次の作業に活かす",
  "Lesson {n} of {total}": "学習 {n} / {total}",
  "Suggested because this lesson is ready to revisit.": "復習の時期なので、この学びを選びました。",
  "Explore related ideas": "関連する考え方を見る",
  "Related by shared topics. Compare the causes before assuming the same fix applies.": "共通のトピックを持つ事例です。同じ対処法を使う前に、原因を比べましょう。",
  "No saved work notes yet": "保存した作業メモはまだありません",
  "After a case, keep a small checklist or reasoning habit for your next task.": "事例を読んだら、次の作業に役立つ短いチェックリストや考え方を残せます。",
  "Work note": "作業メモ",
  "Edit work note": "作業メモを編集",
  "The source lesson changed. Review this work note before using it.": "元のナレッジが変更されました。この作業メモを使う前に確認してください。",
  "Remove work note": "作業メモを削除",
  "System design": "システム設計",
  "Frontend": "フロントエンド",
  "Backend": "バックエンド",
  "APIs": "API",
  "Data modeling": "データモデリング",
  "Databases": "データベース",
  "Testing": "テスト",
  "Security": "セキュリティ",
  "DevOps and cloud": "DevOpsとクラウド",
  "Performance": "パフォーマンス",
  "AI and machine learning": "AIと機械学習",
  "Mobile development": "モバイル開発",
  "Languages and concurrency": "言語と並行処理",
  "Your learning interests": "関心のある学習分野",
  "Picked up from your questions": "あなたの質問から見つけた関心",
  "All categories": "すべての分野",
  "Other lessons": "その他の学び",
  "Lesson categories": "学びの分野",
  "From your questions": "あなたの質問から",
  "All lessons by category": "分野別の学び一覧",
  "Lessons can belong to more than one category. Your interests put relevant categories first.": "学びが複数の分野に属する場合もあります。関心のある分野から順に表示します。",
  "Browse {topic}": "{topic}の一覧を見る",
  "Back to lesson lists": "学びの一覧に戻る",
  "Search your lessons…": "学びを検索…",
  "Search your lessons": "学びを検索",
  "No matching lessons": "一致する学びはありません",
  "Try another search or browse all categories.": "別の言葉で検索するか、すべての分野をご覧ください。",
  "Lessons appear automatically as your sessions are analyzed.": "セッションの分析に合わせて、学びが自動で追加されます。",
  "New": "未読",
  "Read": "既読",
  "Ready to revisit": "復習の時期",
  "Saved note": "メモ保存済み",
  "Mark as read": "既読にする",
  "Ready to revisit in three days. You can open it anytime.": "3日後に復習の目印が付きます。いつでも読み返せます。",
  "Why these topics?": "この分野を選んだ理由",
  "Your recent questions and requests for explanations shape these suggestions. They aren't a skill rating.": "最近の質問や説明の依頼から選んでいます。スキルの評価ではありません。",
  "As you ask about concepts and tradeoffs, your interests will appear here automatically.": "概念やトレードオフについて質問すると、関心のある分野が自動で表示されます。",
  "Learning topic": "学習分野",
  "All learning topics": "すべての学習分野",
  "Suggested because you asked about {topic}.": "{topic}について質問していたので選びました。",
  "See how it works": "仕組みを図で見る",
};
